line-length = 100
output-format = "concise"

[lint]
preview = true
extend-select = ["I", "D", "DOC", "B", "A", "COM", "C4", "DTZ", "EM", "EXE", "FA", "INT", "ISC", "ICN", "PIE", "PYI", "Q", "RET", "SLF", "SIM", "SLOT", "TID", "TC", "ARG", "PTH", "FLY", "NPY", "PD", "N", "PERF", "E", "W", "F", "PLC", "PLE", "UP", "FURB", "RUF", "TRY"]
extend-ignore = ["COM812", "D203", "D213", "D400", "D413", "DOC501", "E266", "EM101", "PLC1901", "RET504", "SIM102", "SIM108", "TRY002", "TRY003", "TRY300"]

[lint.pycodestyle]
max-line-length = 100

[format]
docstring-code-format = false
