#!/bin/sh

#
# This file simply redirects all passed arguments
# to checkers.util.CheckerDevelMain
#
# This script loads the .class files found in the
# build directory before it uses any jar files so
# that a user does not have to repackage the whole
# project to debug changes
#

mydir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      mydir=`cygpath -m $mydir`
      ;;
esac

binaryDir="${mydir}"/../binary

cfDir="${mydir}"/../..
# Put "checkers" last, as "ant bindist" puts other projects
# into the checkers/build directory.
buildDirs="${cfDir}"/dataflow/build:"${cfDir}"/javacutils/build:"${cfDir}"/javaparser/build:"${cfDir}"/checkers/build

eval "java" \
     "-DCheckerDevelMain.cp=${buildDirs} -DCheckerDevelMain.bcp= -DCheckerDevelMain.binary=${binaryDir}" \
     "-classpath ${buildDirs} checkers.util.CheckerDevelMain" "$@"
