nonnull:
	javac -cp ../lib/checkers.jar -processor org.checkerframework.checker.nullness.NullnessChecker -sourcepath src src/checkers/nonnull/NonnullAnnotatedTypeFactory.java

framework:
	javac -cp ../lib/checkers.jar -processor org.checkerframework.checker.nullness.NullnessChecker -sourcepath src src/checkers/types/InternalAnnotationScanner.java
