#!/bin/sh

# This command counts the frequency of each distinct reason for warning
# suppressions.
# Invoke it like this:
#   count-suppressions nullness

# If warning suppression text contains a colon, it prints only the text
# before the colon, under the assumption that the initial text is a
# category name.

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 TYPESYSTEM" >&2
  exit 1
fi

regex="$1"

# If argument is a compound checker, make the regex match them all.
if [ "$regex" = "nullness" ]; then
    regex="\(nullness\|initialization\|keyfor\)"
fi
if [ "$regex" = "index" ]; then
    regex="\(index\|lowerbound\|upperbound\)"
fi

# Implementation notes:
# These are the two types of matching lines:
# Matching lines:
#  * "KEY"  (for @SuppressWarnings, but don't match "@SuppressWarnings"
#    because that might be on the previous line)
#  * @AssumeAssertion(key)

echo "regex=${regex}"

tmpfile=$(mktemp /tmp/count-suppressions.XXXXXX)
grep -n --recursive --include='*.java' "\"${regex}\"\|@AssumeAssertion(${regex})" > ${tmpfile}
echo -n "Total: "
cat ${tmpfile} | wc -l
cat ${tmpfile} \
    | sed 's/.*\/\/ //g' \
    | sed "s/.*@AssumeAssertion(nullness)[ :]*\([^\"]\+\)\"/\1/g" \
    | sed 's/\([^0-9]\): [^:].*/\1/' \
    | sort | uniq -c | sort -rg
rm -f ${tmpfile}
