# Create a Docker image that is ready to run the main Checker Framework tests,
# using JDK 21.

# "ubuntu" is the latest LTS release.  "ubuntu:rolling" is the latest release.
# Both might lag behind; as of 2024-11-16, ubuntu:rolling was still 24.04 rather than 24.10.
FROM ubuntu
LABEL org.opencontainers.image.authors="Michael Ernst <mernst@cs.washington.edu>"

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt update" and "apt install" and "apt cleanup" in the same RUN command.
#  * Do not run "apt upgrade"; instead get upstream to update.

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt -qqy update \
&& apt -qqy install locales \
&& rm -rf /var/lib/apt/lists/* \
&& locale-gen "en_US.UTF-8"
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# Always install JDK 21 to compile the code, even if tests run under a different JDK.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt -qqy update \
&& apt -qqy install \
  openjdk-21-jdk
ENV JAVA21_HOME=/usr/lib/jvm/java-21-openjdk-amd64

# Known good combinations of JTReg and the JDK appear at https://builds.shipilev.net/jtreg/ .

# Dependencies for building and running the Checker Framework.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt -qqy update \
&& apt -qqy install \
  ant \
  cpp \
  git \
  graphviz \
  jq \
  jtreg8 \
  libcurl3-gnutls \
  make \
  python3-requests \
  python3-setuptools \
  unzip \
  wget

# The checksum is the .sha512 file beside the tarball in the URL below.
# Update it whenever the Maven version defined above changes.
RUN export DEBIAN_FRONTEND=noninteractive \
&& cd /opt \
&& wget https://archive.apache.org/dist/maven/maven-4/4.0.0-rc-6/binaries/apache-maven-4.0.0-rc-6-bin.tar.gz \
&& echo "3fba58e1c345a5aa1dbacfa7aceaf7b1a0fa9626e368eec4814fa7a7ebf0fe74f0e41481faef77f95d8738f9c1365f918c8b8c94d7c28656f067db61a8af7f2e  apache-maven-4.0.0-rc-6-bin.tar.gz" | sha512sum --check --strict \
&& tar xzf apache-maven-4.0.0-rc-6-bin.tar.gz \
&& rm apache-maven-4.0.0-rc-6-bin.tar.gz
ENV PATH="/opt/apache-maven-4.0.0-rc-6/bin:$PATH"

# Install the JDK.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt -qqy update \
&& apt -qqy install \
  openjdk-21-jdk \
&& update-java-alternatives --set java-1.21.0-openjdk-amd64
ENV JAVA21_HOME=/usr/lib/jvm/java-21-openjdk-amd64

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt -y autoremove \
&& apt -y clean \
&& rm -rf /var/lib/apt/lists/*
