# Create a Docker image that is ready to run the main Checker Framework tests,
# using JDK 7.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN apt-get -qqy update && apt-get -qqy install \
  software-properties-common \
&& add-apt-repository ppa:openjdk-r/ppa \
&& apt-get -qqy update && apt-get -qqy install \
  ant \
  cpp \
  git \
  gradle \
  make \
  mercurial \
  unzip \
  openjdk-7-jdk \
&& apt-get -qqy remove openjdk-8-jre-headless:amd64 \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
