# Create a Docker image that is ready to run the full Checker Framework tests,
# including building the manual and Javadoc.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN apt-get -qqy update && apt-get -qqy install \
  ant \
  dia \
  git \
  hevea \
  librsvg2-bin \
  make \
  mercurial \
  texlive-fonts-recommended \
  texlive-latex-base \
  texlive-latex-extra \
  texlive-latex-recommended \
  unzip \
  openjdk-7-jdk \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
