# Create a Docker image that is ready to run the full Checker Framework tests,
# including building the manual and Javadoc.
# But it's used primarily for running miscellaneous tests such as the manual
# and Javadoc.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

## Keep this file in sync with ../../docs/manual/troubleshooting.tex

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update && apt-get -qqy install \
  ant \
  cpp \
  git \
  gradle \
  libcurl3-gnutls \
  make \
  maven \
  mercurial \
  unzip \
  wget \
  openjdk-8-jdk \
&& update-java-alternatives --set java-1.8.0-openjdk-amd64 \
&& apt-get -qqy install \
  dia \
  hevea \
  imagemagick \
  jq \
  latexmk \
  librsvg2-bin \
  maven \
  python-pip \
  rsync \
  texlive-font-utils \
  texlive-fonts-recommended \
  texlive-latex-base \
  texlive-latex-extra \
  texlive-latex-recommended \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& pip install html5validator
