# Create a Docker image that is ready to run the full Checker Framework tests,
# including building the manual and Javadoc.
# But it's used primarily for running miscellaneous tests such as the manual
# and Javadoc.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN apt-get -qqy update && apt-get -qqy install \
  software-properties-common \
&& add-apt-repository ppa:openjdk-r/ppa \
&& apt-get -qqy update && apt-get -qqy install \
  ant \
  cpp \
  git \
  gradle \
  make \
  mercurial \
  unzip \
  wget \
  default-jdk \
&& apt-get -qqy install \
  dia \
  hevea \
  librsvg2-bin \
  maven \
  texlive-fonts-recommended \
  texlive-latex-base \
  texlive-latex-extra \
  texlive-latex-recommended \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
