#!/bin/sh

#
# This file simply redirects all passed arguments
# to org.checkerframework.framework.util.CheckerDevelMain
#
# This script loads the .class files found in the
# build directory before it uses any jar files so
# that a user does not have to repackage the whole
# project to debug changes.
#
# This script also has debug arguments set up
# to allow remote debugging of the framework on port
# 5005
#

mydir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      mydir=`cygpath -m $mydir`
      ;;
esac

binaryDir="${mydir}"/../binary

#Langtools bin dir
ltBinDir="${mydir}"/../../../jsr308-langtools/build/classes
jdkPaths="${mydir}"/../jdk/annotated

cfDir="${mydir}"/../..
# Put "checker" last, as "ant bindist" puts other projects
# into the checker/build directory.
buildDirs="${cfDir}"/dataflow/build:"${cfDir}"/javacutil/build:"${cfDir}"/javaparser/build:"${cfDir}"/checker/build

eval "java" \
     "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005" \
     "-DCheckerDevelMain.cp=${buildDirs} " \
     "-DCheckerDevelMain.compile.bcp=${jdkPaths} " \
     "-DCheckerDevelMain.runtime.bcp=${ltBinDir} " \
     "-DCheckerDevelMain.binary=${binaryDir}" \
     "-classpath ${buildDirs} " \
     "org.checkerframework.framework.util.CheckerDevelMain" "$@"
