#!/usr/bin/env python

"""Outputs a dot graph of the type hierarchy.

Must be run in a qual/ directory that contains type qualifier definitions (in
.java files).
"""

import re
import subprocess
import tempfile
from pathlib import Path

subtypeof_pattern = re.compile(r"@SubtypeOf\(\{?([^})]*)\}?\)", re.MULTILINE)

with tempfile.NamedTemporaryFile(mode="w+", delete=False) as tmp:
    print(tmp.name)

    tmp.write("digraph TypeHierarchy {\n")
    tmp.write("rankdir=BT\n")

    for filename in Path.cwd().glob("*.java"):
        # print(filename)
        data = Path(filename).read_text()
        # print(data)
        match = subtypeof_pattern.search(data)
        if match:
            # print(match)
            supertypes = match.group(1).strip()
            # print(f"supertypes = {supertypes}")
            if supertypes:
                typename = Path(filename).stem
                for supertype in supertypes.split(","):
                    supertype = supertype.strip()
                    # print(f"supertype: {supertype}")
                    assert supertype.endswith(".class")
                    supertype = supertype.removesuffix(".class")
                    tmp.write(f"{typename} -> {supertype}\n")

    tmp.write("}\n")

    # It is essential to close the file, or the shell commands cannot read it
    tmp.close()

    # subresult = subprocess.run(["cat", tmp.name])

    subresult = subprocess.run(
        ["dot", "-Tpdf", tmp.name, "-o", "type-hierarchy.pdf"],
        capture_output=True,  # Python >= 3.7 only
        text=True,  # Python >= 3.7 only
        check=True,
    )

    Path.unlink(Path(tmp.name))
