varinfo:
	javac -cp src:../lib/checkers.jar -processor org.checkerframework.checker.interned.InternedChecker -sourcepath src src/daikon/VarInfo.java -Alint=-dotequals

fileio:
	javac -cp src:../lib/checkers.jar -processor org.checkerframework.checker.interned.InternedChecker -sourcepath src src/daikon/FileIO.java -Alint=-dotequals
