#!/bin/sh

#
# This file simply redirects all passed arguments
# to checkers.util.CheckerMain
#

mydir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      mydir=`cygpath -m $mydir`
      ;;
esac

eval "java" "-cp /Users/garrett/Projects/JavaTypes/jsr308/checker-framework-dff-boxing/checkers/tests/build" "-jar" "${mydir}"/checkers.jar "$@"
