version: 1

# The com.amazonaws:aws-java-sdk-* dependencies are updated every day.
# That is too many pull requests.

updates:
  - package-manager: "java:gradle"
    directory: "/"
    ignore-updates:
      - match:
          dependency-name: "com.amazonaws:aws-java-sdk-*"
