version: 2

# The com.amazonaws:aws-java-sdk-* dependencies are updated every day.
# That is too many pull requests.

updates:
  - package-ecosystem: "java:gradle"
    directory: "/"
    ignore:
      - dependency-name: "com.amazonaws:aws-java-sdk-*"
