version: 2
updates:
  - package-ecosystem: "java:gradle"
    directory: "/"
    ignore:
      # This dependency is updated every day.  That is too many pull requests.
      - dependency-name: "com.amazonaws:aws-java-sdk-*"
