factory:
	javac -cp ../lib/checkers.jar -processor checkers.igj.IGJChecker -sourcepath src src/checkers/types/AnnotatedTypeFactory.java

location:
	javac -cp ../lib/checkers.jar -processor checkers.igj.IGJChecker -sourcepath src src/checkers/types/AnnotationLocation.java
