checker-framework-dataflow-manual.pdf: checker-framework-dataflow-manual.tex content.tex examples
	pdflatex checker-framework-dataflow-manual
	pdflatex checker-framework-dataflow-manual

clean:
	\rm -f checker-framework-dataflow-manual.aux checker-framework-dataflow-manual.log checker-framework-dataflow-manual.out checker-framework-dataflow-manual.pdf
