/* JS */ gapi.loaded_0(function(_){var window=this;
_.C=function(a,c,f){a=a.split(".");f=f||_.D;a[0]in f||!f.execScript||f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)a.length||void 0===c?f=f[g]?f[g]:f[g]={}:f[g]=c};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var f=Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.kf=function(a){return void 0!==a};_.ea=function(a){return"array"==(0,_.da)(a)};_.re=function(a){var c=(0,_.da)(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.fa=function(a){return"string"==typeof a};var ia=function(a,c,f){return a.call.apply(a.bind,arguments)};
var la=function(a,c,f){if(!a)throw Error();if(2<arguments.length){var g=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.H=function(a,c,f){_.H=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:la;return _.H.apply(null,arguments)};
_.ma=function(a,c){var f=Array.prototype.slice.call(arguments,1);return function(){var c=f.slice();c.push.apply(c,arguments);return a.apply(this,c)}};_.J=function(a,c){function f(){}f.prototype=c.prototype;a.T=c.prototype;a.prototype=new f;a.prototype.constructor=a};var _DumpException=function(a){throw a;};_.na=_.na||{};_.D=this;_.oa="closure_uid_"+(1E9*Math.random()>>>0);_.pa=Date.now||function(){return+new Date}; Function.prototype.bind=Function.prototype.bind||function(a,c){if(1<arguments.length){var f=Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.H.apply(null,f)}return(0,_.H)(this,a)};
_.Kh=window.gapi||{};_.ra=window.gadgets||{};_.L=window.osapi=window.osapi||{};_.google=window.google||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:!1},csi:{rate:0.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://apis.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"},appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,
"pos.plusones.getSignupState":!0},requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{":source:":"3p"}});
_.ba=function(a,c){return c};_.d=function(a,c){c=(0,_.ba)(a,c);(0,_.C)(a,c,void 0)};_.N=function(a,c,f){return a[c]=a[c]||f};_.ca=function(a){return"function"===typeof a};_.gb=function(a){return String(a).replace(hb,"&amp;").replace(ib,"&lt;").replace(jb,"&gt;").replace(kb,"&quot;").replace(lb,"&#39;")};_.O=function(){var a;if((a=Object.create)&&_.ta.test(a))a=a(null);else{a={};for(var c in a)a[c]=void 0}return a};_.Qa=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};
_.Ra=function(a,c){a=a||{};for(var f in a)(0,_.Qa)(a,f)&&(c[f]=a[f])};_.fb=function(a,c){if(!a)throw Error(c||"");};_.Ua=function(a,c,f){var g=RegExp("([#].*&|[#])"+c+"=([^&#]*)","g");c=RegExp("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.bb=function(a){a=a.match(cb);var c=(0,_.O)();c.yc=a[1];c.mb=a[3]?[a[3]]:[];c.Vf=a[5]?[a[5]]:[];return c};
_.va=function(a){a=a?a.split("&"):[];for(var c=[],f=0;f<a.length;f++){var g=a[f].split("=",2);c.push([(0,window.decodeURIComponent)(g[0]),(0,window.decodeURIComponent)(g[1])])}return c};_.ab=function(a){return a.yc+(0<a.mb.length?"?"+a.mb.join("&"):"")+(0<a.Vf.length?"#"+a.Vf.join("&"):"")};var $a=function(a,c){var f=[];if(a)for(var g in a)if((0,_.Qa)(a,g)&&null!=a[g]){var h=c?c(a[g]):a[g];f.push((0,window.encodeURIComponent)(g)+"="+(0,window.encodeURIComponent)(h))}return f};
_.db=function(a,c,f,g){a=(0,_.bb)(a);a.mb.push.apply(a.mb,$a(c,g));a.Vf.push.apply(a.Vf,$a(f,g));return(0,_.ab)(a)};_.ua=function(a,c){var f="";2E3<c.length&&(f=c.substring(2E3),c=c.substring(0,2E3));var g=a.createElement("div"),h=a.createElement("a");h.href=c;g.appendChild(h);g.innerHTML=g.innerHTML;c=String(g.firstChild.href);g.parentNode&&g.parentNode.removeChild(g);return c+f};_.xa=function(a){return aB.test(a)};_.Va=function(a,c,f){Sa(a,c,f,"add","at")};
_.Ka=function(a,c,f){Sa(a,c,f,"remove","de")};var Sa=function(a,c,f,g,h){if(a[g+"EventListener"])a[g+"EventListener"](c,f,!1);else if(a[h+"tachEvent"])a[h+"tachEvent"]("on"+c,f)};_.eb=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.Za=function(a){return _.Hb.dpo?_.Hb.h:(0,_.Ua)(a,"jsh",_.Hb.h)};_.cc=function(a){return(0,_.Ua)(a,"_bsh",_.Hb.bsh)};_.Wc=function(){return _.Hb.onl};_.le=function(a){_.Hb.onl=a};_.me=function(){return!!_.Hb.oa};
var ya=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};var za=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};var Aa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};var Ba=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!Aa(a[f])&&!Aa(c[f])?Ba(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=Aa(c[f])?[]:{},Ba(a[f],c[f])):a[f]=c[f])};
var Da=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c;try{c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new Function("return ("+a+"\n)"))()}catch(g){}if("object"===typeof c)return c;try{c=(new Function("return ({"+a+"\n})"))()}catch(h){}return"object"===typeof c?c:{}}};
var Ea=function(a){za(!0);var c=window.___gcfg,f=ya("cu");if(c&&c!==window.___gu){var g={};Ba(g,c);f.push(g);window.___gu=c}var c=ya("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[];l.push.apply(l,ya("us"));for(var b=0;b<h.length;++b)for(var q=h[b],t=0;t<l.length;++t)q.src&&0==q.src.indexOf(l[t])&&g.push(q);0==g.length&&0<h.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||(g[h].setAttribute("gapi_processed",
!0),(l=g[h])?(b=l.nodeType,l=3==b||4==b?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=void 0,(l=Da(l))&&c.push(l));a&&(g={},Ba(g,a),f.push(g));g=ya("cd");a=0;for(c=g.length;a<c;++a)Ba(za(),g[a]);g=ya("ci");a=0;for(c=g.length;a<c;++a)Ba(za(),g[a]);a=0;for(c=f.length;a<c;++a)Ba(za(),f[a])};_.P=function(a,c){if(!a)return za();for(var f=a.split("/"),g=za(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&void 0!==g?g:c};
_.Fa=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,b=h.length;l<b-1;++l)var q={},g=g[h[l]]=q;g[h[l]]=c}Ea(f)};var Ga=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.N)(_.Hb,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};
var lb;var kb;var jb;var ib;var hb;_.Ia=window;_.Ja=window.document;_.sb=_.Ia.location;_.ta=/\[native code\]/;hb=/&/g;ib=/</g;jb=/>/g;kb=/"/g;lb=/'/g;_.Yi=(0,_.N)(_.Ia,"gapi",{});var cb=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/,aB=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;_.Hb=(0,_.N)(_.Ia,"___jsl",(0,_.O)());(0,_.N)(_.Hb,"I",0);(0,_.N)(_.Hb,"hel",10);Ga&&Ga();Ea();(0,_.d)("gapi.config.get",_.P);(0,_.d)("gapi.config.update",_.Fa);
var Wj;var Bh;var Tj;var Pa;var Na;var vi;var Bj;var Dh;var pi;var ci;var sh;_.jd=function(a){return!!a&&"object"===typeof a&&_.ta.test(a.push)};_.mf=function(a,c,f){if(a){(0,_.fb)((0,_.jd)(a),"arrayForEach was called with a non array value");for(var g=0;g<a.length;g++)c.call(f,a[g],g)}};_.DC=function(a,c,f){if(a)if((0,_.jd)(a))(0,_.mf)(a,c,f);else{(0,_.fb)("object"===typeof a,"objectForEach was called with a non object value");f=f||a;for(var g in a)(0,_.Qa)(a,g)&&void 0!==a[g]&&c.call(f,a[g],g)}};
var Xf=function(a){a=a.sort();for(var c=[],f=void 0,g=0;g<a.length;g++){var h=a[g];h!=f&&c.push(h);f=h}return c};var rh=function(){var a=[],c=_.Hb.H;c&&(0,_.DC)(c,function(c){a.push.apply(a,c.L)});return Xf(a)};_.wd=function(a){if(_.ta.test(Object.keys))return Object.keys(a);var c=[],f;for(f in a)(0,_.Qa)(a,f)&&c.push(f);return c};
var La=function(a){if(void 0===sh){var c=(0,_.P)("report")||{},f=c.rate,g=Math.random();if(sh="number"===typeof f&&f>g)Bh["rate."+f+"-"+g]=!0,Dh=c.timeout||1E3,ci=c.host||"https://plus.google.com",pi=c.path||"/_/widget/report",vi=c.apis||[]}if(!sh)return!1;if(vi)for(c=0;c<vi.length;c++)if(RegExp("^"+vi[c]+"$").test(a))return!0;return!1};var Ma=function(a){delete Na[a]};
var fj=function(){Bj&&(_.Ia.clearTimeout(Bj),Bj=0);Bj=_.Ia.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var c=(0,_.wd)(Bh).join(":");a=[ci,pi,"?api=",(0,window.encodeURIComponent)(c),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(rh().join(":"))].join("");Bh=(0,_.O)();var c=new window.Image,f=Pa++;Na[f]=c;c.onload=c.onerror=(0,_.ma)(Ma,f);c.src=a;Bj=0},Dh)};Na={};Pa=0;Tj=(0,_.O)();Bh=(0,_.O)();Wj=_.ba; _.ba=function(a,c){var f=Wj(a,c);(0,_.ca)(c)&&La(a)&&(f=function(f){Tj[a]||(Bh[a]=!0,Tj[a]=!0,fj());return c.apply(this,arguments)});return f};


_.Wa={go:{},ca:{}};_.Xa={go:{},ca:{}};(0,_.d)("gapi.plusone.render",_.Xa.ca);(0,_.d)("gapi.plusone.go",_.Xa.go);(0,_.d)("googleapisv0.plusone.go",_.Wa.go);(0,_.d)("googleapisv0.plusone.render",_.Wa.ca);
_.Rb=window.gapi&&window.gapi.util||{};
_.Rb.Pq=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("Pa");var f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!== h)f=":"+h}return a+"://"+c+f};

_.kd=function(a){_.Kd&&_.Kd.log&&_.Kd.log(a)};_.ke=function(){};_.Kd=window.console;
if(window.JSON&&window.JSON.parse&&window.JSON.stringify)_.Kb={parse:function(a){try{return window.JSON.parse(a)}catch(c){return!1}},stringify:window.JSON.stringify};window.JSON&&window.JSON.parse&&window.JSON.stringify||(_.Kb=function(){function a(f){var g,h,l;g=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof f){case "string":return g.test(f)?'"'+f.replace(g,function(a){var f=c[a];if(f)return f;f=a.charCodeAt();return"\\u00"+Math.floor(f/16).toString(16)+(f%16).toString(16)})+'"':'"'+f+'"';case "number":return(0,window.isFinite)(f)?String(f):"null";case "boolean":case "null":return String(f);case "object":if(!f)return"null";g=[];if("number"===typeof f.length&&!f.propertyIsEnumerable("length")){l=
f.length;for(h=0;h<l;h+=1)g.push(a(f[h])||"null");return"["+g.join(",")+"]"}for(h in f)!/___$/.test(h)&&f.hasOwnProperty(h)&&"string"===typeof h&&(l=a(f[h]))&&g.push(a(h)+":"+l);return"{"+g.join(",")+"}"}return""}var c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:a,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g, ""))?eval("("+a+")"):!1}}}());
_.Kb.Ck=function(a){var c={};if(null===a||void 0===a)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];null!==g&&void 0!==g&&(c[f]="string"===typeof g?g:_.Kb.stringify(g))}return c};(0,_.d)("gadgets.json.flatten",_.Kb.Ck);(0,_.d)("gadgets.json.parse",_.Kb.parse);(0,_.d)("gadgets.json.stringify",_.Kb.stringify);(0,_.d)("gadgets.json.flatten",_.Kb.Ck);(0,_.d)("gadgets.json.parse",_.Kb.parse);(0,_.d)("gadgets.json.stringify",_.Kb.stringify);

_.R=_.R||{};
_.Nb=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.R=_.R||{};
(function(){var a=null;_.R.$c=function(c){var f="undefined"===typeof c;if(null!==a&&f)return a;var g={};c=c||window.location.href;var h=c.indexOf("?"),l=c.indexOf("#");c=(-1===l?c.substr(h+1):[c.substr(h+1,l-h-1),"&",c.substr(l+1)].join("")).split("&");for(var h=window.decodeURIComponent?window.decodeURIComponent:window.unescape,l=0,b=c.length;l<b;++l){var q=c[l].indexOf("=");if(-1!==q){var t=c[l].substring(0,q),q=c[l].substring(q+1),q=q.replace(/\+/g," ");try{g[t]=h(q)}catch(v){}}}f&&(a=g);return g}; _.R.$c()})();
(0,_.d)("gadgets.util.getUrlParameters",_.R.$c);
var jz=function(a){this.G=a;this.B=_.Ia;this.qa=this.Ka;if(this.G.$E){this.B=this.G.kq(this.B,this.G.$E);a=this.B.document;var c=a.createElement("script");c.setAttribute("type","text/javascript");c.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(c);this.qa=this.B.doPostMsg}this.ha={};this.M={};a=(0,_.H)(this.wc,this);(0,_.Va)(this.B,"message",a);(0,_.N)(_.Hb,"RPMQ",[]).push(a);this.B!=this.B.parent&&CC(this,this.B.parent,"{h:'"+(0,window.escape)(this.B.name)+
"'}","*")};var lz=function(a,c){var f=null;0===c.indexOf("{h:'")&&c.indexOf("'}")===c.length-2&&(f=(0,window.unescape)(c.substring(4,c.length-2)));return f};var kz=function(a,c){var f=_.Kb.parse(c);return null!==f&&"object"===typeof f&&!!f.g};var CC=function(a,c,f,g){var h=kz(a,f)?"":"!_";(0,_.ke)("gapi.rpc.send("+Qz+"): "+(!f||512>=f.length?f:f.substr(0,512)+"... ("+f.length+" bytes)"));a.qa(c,h+f,g)};var mz=function(){};
var nz=function(a,c){"/"==c.charAt(0)&&(c=c.substring(1),a=_.Ia.top);for(var f=c.split("/");f.length;){var g;g=f.shift();"{"==g.charAt(0)&&"}"==g.charAt(g.length-1)&&(g=g.substring(1,g.length-1));if(".."===g)a=a==a.parent?a.opener:a.parent;else if(".."!==g&&a.frames[g]){if(a=a.frames[g],!("postMessage"in a))throw"Not a window";}else return null}return a};var oz=function(a){return(a=pz[a])&&a.ve};
var qz=function(a){if(a.f in{})return!1;var c=a.t,f=pz[a.r];a=a.origin;return f&&(f.ve===c||!f.ve&&!c)&&(a===f.origin||"*"===f.origin)};var rz=function(a){var c=a.id.split("/"),f=c[c.length-1],g=a.origin;return function(a){var c=a.origin;return a.f==f&&(g==c||"*"==g)}};_.sz=function(a,c,f){a=tz(a);uz[a.name]={Ip:c,lf:a.lf,Us:f||qz};vz()};_.wz=function(a){delete uz[tz(a).name]};var xz=function(a,c){var f=yz["_"+a];f&&f[1](this)&&f[0].call(this,c)};
var zz=function(a){var c=a.c;if(!c)return mz;var f=a.r,g=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,0);a.unshift(f,g+"__cb",null,c);_.Az.apply(null,a)}};var Bz=function(a){Cz=a};var Dz=function(a){Ez[a]||(Ez[a]=_.Ia.setTimeout(function(){Ez[a]=!1;Fz(a)},0))};var Fz=function(a){var c=pz[a];if(c&&c.Tb){var f=c.kj;for(c.kj=[];f.length;)Gz.send(a,_.Kb.stringify(f.shift()),c.origin)}};var tz=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),lf:!0}:{name:a,lf:!1}};
var vz=function(){for(var a=(0,_.P)("rpc/residenceSec")||60,c=(new Date).getTime()/1E3,f=0,g;g=Hz[f];++f){var h=g.qf;if(!h||0<a&&c-g.timestamp>a)Hz.splice(f,1),--f;else{var l=h.s,b=uz[l]||uz["*"];if(b)if(Hz.splice(f,1),--f,h.origin=g.origin,g=zz(h),h.callback=g,b.Us(h)){if("__cb"!==l&&!!b.lf!=!!h.g)break;h=b.Ip.apply(h,h.a);void 0!==h&&g(h)}else(0,_.ke)("gapi.rpc.rejected("+Qz+"): "+l)}}};var Iz=function(a,c,f){Hz.push({qf:a,origin:c,timestamp:(new Date).getTime()/1E3});f||vz()};
var Jz=function(a,c){var f=_.Kb.parse(a);Iz(f,c,!1)};var Kz=function(a){for(;a.length;)Iz(a.shift(),this.origin,!0);vz()};var Lz=function(a){var c=!1;a=a.split("|");var f=a[0];0<=f.indexOf("/")&&(c=!0);return{id:f,origin:a[1]||"*",Ki:c}};
_.Mz=function(a,c,f,g){var h=Lz(a);g&&(_.Ia.frames[h.id]=_.Ia.frames[h.id]||g);a=h.id;if(!pz.hasOwnProperty(a)){f=f||null;g=h.origin;if(".."===a)g=_.Rb.Pq(Oz),f=f||Pz;else if(!h.Ki){var l=_.Ja.getElementById(a);l&&(l=l.src,g=_.Rb.Pq(l),f=f||Nz(l).rpctoken)}"*"===h.origin&&g||(g=h.origin);pz[a]={ve:f,kj:[],origin:g,hs:c,xm:function(){var c=a;pz[c].Tb=1;Fz(c)}};Gz.sf(a,pz[a].xm)}return pz[a].xm};
_.Az=function(a,c,f,g){a=a||"..";(0,_.Mz)(a);a=a.split("|",1)[0];var h=[].slice.call(arguments,3),l=c,b=f,q=Qz,t=Pz,v=pz[a],w=q,A=Lz(a);if(v&&".."!==a){if(A.Ki){if(!(w=pz[a].hs)){for(var w=null,w=Cz?Cz.substring(1).split("/"):[Qz],t=w.length-1,F=_.Ia.parent;F!==_.Ia.top;){var z=F.parent;if(!t--){for(var I=null,E=z.frames.length,K=0;K<E;++K)z.frames[K]==F&&(I=K);w.unshift("{"+I+"}")}F=z}w="/"+w.join("/")}}else w=q="..";t=v.ve}v=l;b&&A?(F=qz,A.Ki&&(F=rz(A)),yz["_"+ ++Rz]=[b,F],A=Rz):A=null;h={s:v,f:q,
r:w,t:t,c:A,a:h};l=tz(l);h.s=l.name;h.g=l.lf;pz[a].kj.push(h);Dz(a)};jz.prototype.wc=function(a){var c=String(a.data);(0,_.ke)("gapi.rpc.receive("+Qz+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));var f=0!==c.indexOf("!_");f||(c=c.substring(2));var g=kz(this,c);if(!f&&!g){if(!g&&(f=lz(this,c))){if(this.ha[f])this.ha[f]();else this.M[f]=1;return}var h=a.origin,l=this.G.zp;_.Ia.setTimeout(function(){l(c,h)},0)}}; jz.prototype.sf=function(a,c){".."===a||this.M[a]?(c(),delete this.M[a]):this.ha[a]=c};jz.prototype.Ka=function(a,c,f){a.postMessage(c,f)};jz.prototype.send=function(a,c,f){(a=this.G.kq(this.B,a))&&CC(this,a,c,f)};
var Rz=0,Hz=[],pz={},uz={},Nz=_.R.$c,Sz=Nz(),Pz=Sz.rpctoken,Oz=Sz.parent||_.Ja.referrer,xl=Sz.rly,Qz=xl||(_.Ia!==_.Ia.top||_.Ia.opener)&&_.Ia.name||"..",Cz=null,Ez={},Gz={send:mz,sf:mz},yz={};if("function"===typeof _.Ia.postMessage||"object"===typeof _.Ia.postMessage)Gz=new jz({$E:xl?"../"+xl:null,zp:Jz,kq:nz,MN:Qz,$f:oz,dO:Bz}),(0,_.sz)("__cb",xz,function(){return!0}),(0,_.sz)("_processBatch",Kz,function(){return!0}),(0,_.Mz)("..");

_.ak=function(a){var c=(0,_.P)("googleapis.config/sessionIndex");null==c&&(c=window.__X_GOOG_AUTHUSER);if(null==c){var f=window.google;f&&(c=f.authuser)}null==c&&(a=a||window.location.href,c=(0,_.Ua)(a,"authuser")||null,null==c&&(c=(c=a.match(bk))?c[1]:null));return null==c?null:String(c)};_.vk=function(a){var c=(0,_.P)("googleapis.config/sessionDelegate");null==c&&(c=(a=(a||window.location.href).match(wk))?a[1]:null);return null==c?null:String(c)}; _.ol=function(a,c){var f=(0,_.ak)(a)||c,g=(0,_.vk)(a),h="";f&&(h+="u/"+f+"/");g&&(h+="b/"+g+"/");return h||null};
var bk=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//,wk=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;
var wb=function(){};var xb=function(){this.B=[];this.M=[];this.Ka=[];this.ha=[];this.ha[0]=128;for(var a=1;64>a;++a)this.ha[a]=0;this.reset()};
var yb=function(a,c,f){f||(f=0);var g=a.Ka;if((0,_.fa)(c))for(var h=0;16>h;h++)g[h]=c.charCodeAt(f)<<24|c.charCodeAt(f+1)<<16|c.charCodeAt(f+2)<<8|c.charCodeAt(f+3),f+=4;else for(h=0;16>h;h++)g[h]=c[f]<<24|c[f+1]<<16|c[f+2]<<8|c[f+3],f+=4;for(h=16;80>h;h++){var l=g[h-3]^g[h-8]^g[h-14]^g[h-16];g[h]=(l<<1|l>>>31)&4294967295}c=a.B[0];f=a.B[1];for(var b=a.B[2],q=a.B[3],t=a.B[4],v,h=0;80>h;h++)40>h?20>h?(l=q^f&(b^q),v=1518500249):(l=f^b^q,v=1859775393):60>h?(l=f&b|q&(f|b),v=2400959708):(l=f^b^q,v=3395469782), l=(c<<5|c>>>27)+l+t+v+g[h]&4294967295,t=q,q=b,b=(f<<30|f>>>2)&4294967295,f=c,c=l;a.B[0]=a.B[0]+c&4294967295;a.B[1]=a.B[1]+f&4294967295;a.B[2]=a.B[2]+b&4294967295;a.B[3]=a.B[3]+q&4294967295;a.B[4]=a.B[4]+t&4294967295};_.rl=function(){this.B=new xb};
(0,_.J)(xb,wb);xb.prototype.reset=function(){this.B[0]=1732584193;this.B[1]=4023233417;this.B[2]=2562383102;this.B[3]=271733878;this.B[4]=3285377520;this.qa=this.G=0};xb.prototype.update=function(a,c){(0,_.kf)(c)||(c=a.length);for(var f=c-64,g=0,h=this.M,l=this.G;g<c;){if(0==l)for(;g<=f;)yb(this,a,g),g+=64;if((0,_.fa)(a))for(;g<c;){if(h[l]=a.charCodeAt(g),++l,++g,64==l){yb(this,h);l=0;break}}else for(;g<c;)if(h[l]=a[g],++l,++g,64==l){yb(this,h);l=0;break}}this.G=l;this.qa+=c};
xb.prototype.xk=function(){var a=[],c=8*this.qa;56>this.G?this.update(this.ha,56-this.G):this.update(this.ha,64-(this.G-56));for(var f=63;56<=f;f--)this.M[f]=c&255,c/=256;yb(this,this.M);for(f=c=0;5>f;f++)for(var g=24;0<=g;g-=8)a[c]=this.B[f]>>g&255,++c;return a};
_.k=_.rl.prototype;_.k.reset=function(){this.B.reset()};_.k.HF=function(a){this.B.update(a)};_.k.pD=function(){return this.B.xk()};_.k.lC=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var c=[],f=0,g=a.length;f<g;++f)c.push(a.charCodeAt(f));this.HF(c)};_.k.Of=function(){for(var a=this.pD(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c};

var mb=function(){var a=(0,_.Wc)();if(!a){a=(0,_.O)();(0,_.le)(a);var c=(0,_.O)();a.e=function(a){var g=c[a];g&&(delete c[a],g())};a.a=function(a,g){c[a]=g};a.r=function(a){delete c[a]}}return a};var nb=function(a,c){var f=c.onload;return(0,_.ca)(f)?(mb().a(a,f),f):null};var ob=function(a){(0,_.fb)(/^\w+$/.test(a),"Unsupported id - "+a);mb();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};var pb=function(a){mb().r(a)};
_.yl=function(a,c){var f,g=0;do f=c.id||["I",ub++,"_",(new Date).getTime()].join("");while(a.getElementById(f)&&5>++g);(0,_.fb)(5>g,"Error creating iframe id");return f};
_.qa=function(a,c,f,g){var h={},l={};(0,_.Ra)(g.queryParams||{},h);(0,_.Ra)(g.fragmentParams||{},l);var b=g.pfname,q=(0,_.O)();q.id=f;q.parent=a.location.protocol+"//"+a.location.host;f=(0,_.Ua)(a.location.href,"parent");b=b||"";!b&&f&&(b=(0,_.Ua)(a.location.href,"id",""),f=(0,_.Ua)(a.location.href,"pfname",""),b=b?f+"/"+b:"");q.pfname=b;(0,_.Ra)(q,l);(q=(0,_.Ua)(c,"rpctoken")||h.rpctoken||l.rpctoken)||(q=l.rpctoken=g.rpctoken||String(Math.round(1E8*(0,_.zl)())));g.rpctoken=q;q=a.location.href;a=
(0,_.O)();(b=(0,_.cc)(q))&&(a._bsh=b);(q=(0,_.Za)(q))&&(a.jsh=q);g.hintInFragment?(0,_.Ra)(a,l):(0,_.Ra)(a,h);return(0,_.db)(c,h,l,g.paramsSerializer)};var hc=function(a){(0,_.fb)(!a||(0,_.xa)(a),"Illegal url for new iframe - "+a)};
_.Al=function(a,c,f,g,h){hc(f.src);var l,b=nb(g,f),q=b?ob(g):"";try{l=a.createElement('<iframe frameborder="'+(0,_.gb)(String(f.frameborder))+'" scrolling="'+(0,_.gb)(String(f.scrolling))+'" '+q+' name="'+(0,_.gb)(String(f.name))+'"/>')}catch(t){l=a.createElement("iframe"),b&&(l.onload=function(){l.onload=null;b.call(this)},pb(g))}for(var v in f)a=f[v],"style"===v&&"object"===typeof a?(0,_.Ra)(a,l.style):rb[v]||l.setAttribute(v,String(a));(v=h&&h.beforeNode||null)||h&&h.dontclear||(0,_.eb)(c);c.insertBefore(l,
v);l=v?v.previousSibling:c.lastChild;f.allowtransparency&&(l.allowTransparency=!0);return l};var jc=function(a,c){if(!kc||(0,_.P)("oauth-flow/authAware")){var f=(0,_.ak)()||"0",g=(0,_.vk)(),h=(0,_.ol)(void 0,f),l=(0,_.P)("oauth-flow/authAware")?"isLoggedIn":"googleapis.config/signedIn";(l=!1===(0,_.P)(l)?"_/im/":"")&&(h="");kc={socialhost:(0,_.P)("iframes/:socialhost:"),session_index:f,session_delegate:g,session_prefix:h,im_prefix:l}}return kc[c]||""};
_.mc=function(a){return(0,_.ua)(_.Ja,a.replace(nc,jc))};_.Bl=function(a){var c=a;zd.test(a)&&(c=(0,_.P)("iframes/"+c.substring(1)+"/url"),(0,_.fb)(!!c,"Unknown iframe url config for - "+a));return(0,_.mc)(c)};
_.tb=function(a,c,f){var g=f||{};f=g.attributes||{};(0,_.fb)(!g.allowPost||!f.onload,"onload is not supported by post iframe");a=(0,_.Bl)(a);f=c.ownerDocument||_.Ja;var h=(0,_.yl)(f,g);a=(0,_.qa)(f,a,h,g);var l=(0,_.O)();(0,_.Ra)(_.vb,l);(0,_.Ra)(g.attributes,l);l.name=l.id=h;l.src=a;g.eurl=a;if((g||{}).allowPost&&2E3<a.length){var b=(0,_.bb)(a);l.src="";l["data-postorigin"]=a;a=(0,_.Al)(f,c,l,h);var q;if(-1!=window.navigator.userAgent.indexOf("WebKit")){q=a.contentWindow.document;q.open();var l=
q.createElement("div"),t={},v=h+"_inner";t.name=v;t.src="";t.style="display:none";(0,_.Al)(f,l,t,v,g)}g=(0,_.va)(b.mb[0]);b.mb=[];l=(0,_.ab)(b);b=f.createElement("form");b.action=l;b.method="POST";b.target=h;b.style.display="none";for(h=0;h<g.length;h++)l=f.createElement("input"),l.type="hidden",l.name=g[h][0],l.value=g[h][1],b.appendChild(l);c.appendChild(b);b.submit();b.parentNode.removeChild(b);q&&q.close();c=a}else c=(0,_.Al)(f,c,l,h,g);return c};var kc;
var ub;var rb;_.vb={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};rb={allowtransparency:!0,onload:!0};ub=0;var zd=/^:[\w]+$/,nc=/:([a-zA-Z_]+):/g;
_.zl=function(){var a;Jb?(a=new _.Ia.Uint32Array(1),Ib.getRandomValues(a),a=Number("0."+a[0])):(a=Ab,a+=(0,window.parseInt)(Gb.substr(0,20),16),Gb=Eb(Gb),a=a/(Bb+Math.pow(16,20)));return a};var zb=function(a){a=a||_.Ia.event;var c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=(new Date).getTime()%1E6*c;Ab=Ab*c%Bb;0<Cb&&++Db==Cb&&(0,_.Ka)(_.Ia,"mousemove",zb)};var Eb=function(a){var c=new _.rl;c.lC(a);return c.Of()};var Ib=_.Ia.crypto,Jb=!1,Cb=0,Db=0,Ab=1,Bb=0,Gb="",Jb=!!Ib&&"function"==typeof Ib.getRandomValues; Jb||(Bb=1E6*(window.screen.width*window.screen.width+window.screen.height),Gb=Eb(_.Ja.cookie+"|"+_.Ja.location+"|"+(new Date).getTime()+"|"+Math.random()),Cb=(0,_.P)("random/maxObserveMousemove")||0,0!=Cb&&(0,_.Va)(_.Ia,"mousemove",zb));


_.R=_.R||{};_.R.Dg=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.R.nf=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.R=_.R||{};
(function(){function a(a,c){return String.fromCharCode(c)}var c={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.R.escape=function(a,c){if(a){if("string"===typeof a)return _.R.Qf(a);if("Array"===typeof a)for(var h=0,l=a.length;h<l;++h)a[h]=_.R.escape(a[h]);else if("object"===typeof a&&c){h={};for(l in a)a.hasOwnProperty(l)&&(h[_.R.Qf(l)]=_.R.escape(a[l],!0));return h}}return a};_.R.Qf=function(a){if(!a)return a;for(var g=[],h,l,b=0,q= a.length;b<q;++b)h=a.charCodeAt(b),l=c[h],!0===l?g.push("&#",h,";"):!1!==l&&g.push(a.charAt(b));return g.join("")};_.R.su=function(c){return c?c.replace(/&#([0-9]+);/g,a):c}})();

_.Ob=_.Ob||{};_.Ob.Xk=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.Ob=_.Ob||{};
(function(){function a(a,f){window.getComputedStyle(a,"").getPropertyValue(f).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Ob.ih=function(){var c=_.Ob.Xk().height,f=window.document.body,g=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&g.scrollHeight)return g.scrollHeight!==c?g.scrollHeight:g.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){c=0;for(f=[window.document.body];0<f.length;){var h=f.shift(),g=h.childNodes;if("undefined"!==
typeof h.style){var l=h.style.overflowY;l||(l=(l=window.document.defaultView.getComputedStyle(h,null))?l.overflowY:null);if("visible"!=l&&"inherit"!=l&&(l=h.style.height,l||(l=(l=window.document.defaultView.getComputedStyle(h,null))?l.height:""),0<l.length&&"auto"!=l))continue}for(h=0;h<g.length;h++){l=g[h];if("undefined"!==typeof l.offsetTop&&"undefined"!==typeof l.offsetHeight)var b=l.offsetTop+l.offsetHeight+a(l,"margin-bottom"),c=Math.max(c,b);f.push(l)}}return c+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(f&&g)return h=g.scrollHeight,l=g.offsetHeight,g.clientHeight!==l&&(h=f.scrollHeight,l=f.offsetHeight),h>c?h>l?h:l:h<l?h:l}})();

_.Rb=_.Rb||{};_.Rb.xh=function(){var a={Nj:"bsh",Uj:"h"};window.___jsl=window.___jsl||{};return{B:function(){return window.___jsl[a.Nj]},Ok:function(){return window.___jsl[a.Uj]},pj:function(c){window.___jsl[a.Nj]=c},ys:function(c){window.___jsl[a.Uj]=c}}}();

_.Mb=function(){function a(a){c(1,a)}function c(a,c){if(!(a<f)&&g)if(2===a&&g.warn)g.warn(c);else if(3===a&&g.error)try{g.error(c)}catch(b){}else g.log&&g.log(c)}_.Lb=function(a){c(2,a)};_.sa=function(a){c(3,a)};_.Fc=function(){};a.INFO=1;a.WARNING=2;a.NONE=4;var f=1,g=window.console?window.console:window.opera?window.opera.postError:void 0;return a}();

_.R=_.R||{};(function(){var a=[];_.R.du=function(c){a.push(c)};_.R.ku=function(){for(var c=0,f=a.length;c<f;++c)a[c]()}})();
_.Pb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&(0,_.Fa)(a());return{Q:function(a,f,g){g&&g((0,_.P)())},get:function(a){return(0,_.P)(a)},update:function(a,f){if(f)throw"Config replacement is not supported";(0,_.Fa)(a)},gb:function(){}}}();
(0,_.d)("gadgets.config.register",_.Pb.Q);(0,_.d)("gadgets.config.get",_.Pb.get);(0,_.d)("gadgets.config.init",_.Pb.gb);(0,_.d)("gadgets.config.update",_.Pb.update);
_.Ub=function(a){if("complete"===_.Ja.readyState)a();else{var c=!1,f=function(){if(!c)return c=!0,a.apply(this,arguments)};_.Ia.addEventListener?(_.Ia.addEventListener("load",f,!1),_.Ia.addEventListener("DOMContentLoaded",f,!1)):_.Ia.attachEvent&&(_.Ia.attachEvent("onreadystatechange",function(){"complete"===_.Ja.readyState&&f.apply(this,arguments)}),_.Ia.attachEvent("onload",f))}};_.ql=function(a,c){var f=(0,_.N)(_.Hb,"watt",(0,_.O)());(0,_.N)(f,a,c)};_.vd=function(a,c){if("complete"!==_.Ja.readyState)try{a()}catch(f){}(0,_.Ub)(c)}; var Qb=Qb||{};Qb.Km=null;Qb.bm=null;Qb.pg=null;Qb.frameElement=null;
Qb=Qb||{};
Qb.Lj||(Qb.Lj=function(){function a(a,c,f){"undefined"!=typeof window.addEventListener?window.addEventListener(a,c,f):"undefined"!=typeof window.attachEvent&&window.attachEvent("on"+a,c);"message"===a&&(window.___jsl=window.___jsl||{},a=window.___jsl,a.RPMQ=a.RPMQ||[],a.RPMQ.push(c))}function c(a){var c=_.Kb.parse(a.data);if(c&&c.f){(0,_.Fc)("gadgets.rpc.receive("+window.name+"): "+a.data);var g=_.T.$d(c.f);h&&("undefined"!==typeof a.origin?a.origin!==g:a.domain!==/^.+:\/\/([^:]+).*/.exec(g)[1])?(0,_.sa)("Invalid rpc message origin. "+
g+" vs "+(a.origin||"")):f(c,a.origin)}}var f,g,h=!0;return{Kk:function(){return"wpm"},B:function(){return!0},gb:function(l,b){_.Pb.Q("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(h=!1)});f=l;g=b;a("message",c,!1);g("..",!0);return!0},sf:function(a){g(a,!0);return!0},call:function(a,c,f){var g=_.T.$d(a),h=_.T.dk(a);g?window.setTimeout(function(){var a=_.Kb.stringify(f);(0,_.Fc)("gadgets.rpc.send("+window.name+"): "+a);h.postMessage(a,g)},0):".."!=a&&(0,_.sa)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
Qb=Qb||{};
Qb.Uf||(Qb.Uf=function(){function a(a,c){function f(){a.apply({},arguments)}rw[c]=rw[c]||f;return ja+"."+c}function c(){if(null===z&&window.document.body&&v){var a=v+"?cb="+Math.random()+"&origin="+Ca+"&jsl=1",f=window.document.createElement("div");f.style.height="1px";f.style.width="1px";a='<object height="1" width="1" id="'+t+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(f);f.innerHTML=a;z=f.firstChild}++K;null!==E&&(null!==z||50<=K)?window.clearTimeout(E):E=window.setTimeout(c,100)}function f(){S[".."]||(q(".."),U++,50<=U&&null!==ka?(window.clearTimeout(ka),ka=null):ka=window.setTimeout(f,100))}function g(){if(null!==z&&z.setup)for(;0<I.length;){var a=I.shift(),c=a.Qs;z.setup(a.ve,".."===c?_.T.lh:c,".."===c?"INNER":"OUTER")}null!==E&&window.clearTimeout(E);E=null}function h(){S[".."]||null!==
ka||(ka=window.setTimeout(f,100))}function l(a,c,f){c=_.T.$d(a);var g=_.T.Wd(a);z["sendMessage_"+(".."===a?_.T.lh:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(z,_.Kb.stringify(f),c);return!0}function b(a,c){var f=_.Kb.parse(a),g=f._scr;g?(F(g,!0),S[g]=!0,".."!==g&&q(g,!0)):window.setTimeout(function(){A(f,c)},0)}function q(a,c){var f=_.T.lh,g={};g._scr=c?"..":f;g._pnt=f;l(a,f,g)}var t="___xpcswf",v=null,w=!1,A=null,F=null,z=null,I=[],E=null,K=0,U=0,ka=null,S={},Ca=window.location.protocol+"//"+window.location.host,
ja,rw=function(){window.___jsl=window.___jsl||{};var a=window.___jsl._fm={};ja="___jsl._fm";return a}();_.Pb.Q("rpc",null,function(a){w&&(v=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(g,"ready");a(h,"setupDone");a(b,"receiveMessage");return{Kk:function(){return"flash"},B:function(){return!0},gb:function(a,c){A=a;F=c;return w=!0},sf:function(a,f){I.push({ve:f,Qs:a});null===z&&null===E&&(E=window.setTimeout(c,100));return!0},call:l,Vo:b,G:g,ha:h}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.T&&_.T||(_.T=window.gadgets.rpc,_.T.Ca=_.T.config,_.T.Q=_.T.register,_.T.Jd=_.T.unregister,_.T.Am=_.T.registerDefault,_.T.aB=_.T.unregisterDefault,_.T.Fk=_.T.forceParentVerifiable,_.T.call=_.T.call,_.T.Rk=_.T.getRelayUrl,_.T.Xg=_.T.setRelayUrl,_.T.Wg=_.T.setAuthToken,_.T.tf=_.T.setupReceiver,_.T.Wd=_.T.getAuthToken,_.T.mj=_.T.removeReceiver,_.T.Qk=_.T.getRelayChannel,_.T.ym=_.T.receive,_.T.zm=_.T.receiveSameDomain,_.T.Pq=_.T.getOrigin,_.T.$d=
_.T.getTargetOrigin,_.T.dk=_.T._getTargetWin,_.T.Uo=_.T._parseSiblingId);else{_.T=function(){function a(){}function c(a,c){if(!Ya[a]){var f=fc;c||(f=te);Ya[a]=f;for(var g=If[a]||[],h=0;h<g.length;++h){var l=g[h];l.t=S[a];f.call(a,l.f,l)}If[a]=[]}}function f(){function a(){Go=!0}Ho||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),Ho=!0)}function g(c,g,h,l,b){S[g]&&S[g]===h||((0,_.sa)("Invalid gadgets.rpc token. "+
S[g]+" vs "+h),a(g,2));b.onunload=function(){rw[g]&&!Go&&(a(g,1),_.T.mj(g))};f();l=_.Kb.parse((0,window.decodeURIComponent)(l))}function h(f,g){if(f&&"string"===typeof f.s&&"string"===typeof f.f&&f.a instanceof Array)if(S[f.f]&&S[f.f]!==f.t&&((0,_.sa)("Invalid gadgets.rpc token. "+S[f.f]+" vs "+f.t),a(f.f,2)),"__ack"===f.s)window.setTimeout(function(){c(f.f,!0)},0);else{f.c&&(f.callback=function(a){_.T.call(f.f,(f.g?"legacy__":"")+"__cb",null,f.c,a)});if(g){var h=l(g);f.origin=g;var b=f.r,q;try{q=
l(b)}catch(t){}b&&q==h||(b=g);f.referer=b}h=(K[f.s]||K[""]).apply(f,f.a);f.c&&"undefined"!==typeof h&&_.T.call(f.f,"__cb",null,f.c,h)}}function l(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==
a)throw Error("Pa");var f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f}function b(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):null}}return null}function q(a){if("undefined"===typeof a||".."===a)return window.parent;var c=b(a);if(c)return window.top.frames[c.id];a=String(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&
c.contentWindow?c.contentWindow:null}function t(a,c){if(!0!==rw[a]){"undefined"===typeof rw[a]&&(rw[a]=0);var f=q(a);".."!==a&&null==f||!0!==fc.sf(a,c)?!0!==rw[a]&&10>rw[a]++?window.setTimeout(function(){t(a,c)},500):(Ya[a]=te,rw[a]=!0):rw[a]=!0}}function v(a){(a=U[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function w(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&(0==c.indexOf("//")?
c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));U[a]=c;"undefined"!==typeof f&&(ka[a]=!!f)}function A(a,c){c=c||"";S[a]=String(c);t(a,c)}function F(a){a=(a.passReferrer||"").split(":",2);wh=a[0]||"none";nk=a[1]||"origin"}function z(a){"true"===String(a.useLegacyProtocol)&&(fc=Qb.pg||te,fc.gb(h,c))}function I(a,c){function f(g){g=g&&g.rpc||{};F(g);var h=g.parentRelayUrl||"",h=l(Ta.parent||
c)+h;w("..",h,"true"===String(g.useLegacyProtocol));z(g);A("..",a)}!Ta.parent&&c?f({}):_.Pb.Q("rpc",null,f)}function E(a,c,f){if(".."===a)I(f||Ta.rpctoken||Ta.ifpctok||"",c);else t:{var g=null;if("/"!=a.charAt(0)){if(!_.R)break t;g=window.document.getElementById(a);if(!g)throw Error("h`"+a);}g=g&&g.src;c=c||_.T.Pq(g);w(a,c);c=_.R.$c(g);A(a,f||c.rpctoken)}}var K={},U={},ka={},S={},Ca=0,ja={},rw={},Ta={},Ya={},If={},wh=null,nk=null,Yw=window.top!==window.self,ok=window.name,pk=window.console,Io=pk&&
pk.log&&function(a){pk.log(a)}||function(){},te=function(){function a(c){return function(){Io(c+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.R&&(Ta=_.R.$c());var Go=!1,Ho=!1,fc=function(){if("flash"==Ta.rpctx)return Qb.Uf;if("rmr"==Ta.rpctx)return Qb.Km;var a="function"===typeof window.postMessage?Qb.Lj:"object"===typeof window.postMessage?Qb.Lj:window.ActiveXObject?Qb.Uf?Qb.Uf:Qb.bm?Qb.bm:Qb.pg:
0<window.navigator.userAgent.indexOf("WebKit")?Qb.Km:"Gecko"===window.navigator.product?Qb.frameElement:Qb.pg;a||(a=te);return a}();K[""]=function(){Io("Unknown RPC service: "+this.s)};K.__cb=function(a,c){var f=ja[a];f&&(delete ja[a],f.call(this,c))};return{Ca:function(c){"function"===typeof c.Mm&&(a=c.Mm)},Q:function(a,c){if("__cb"===a||"__ack"===a)throw Error("i");if(""===a)throw Error("j");K[a]=c},Jd:function(a){if("__cb"===a||"__ack"===a)throw Error("k");if(""===a)throw Error("l");delete K[a]},
Am:function(a){K[""]=a},aB:function(){delete K[""]},Fk:function(){},call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=ok:"/"==a.charAt(0)&&(h=_.T.Pq(window.location.href),h="/"+ok+(h?"|"+h:""));++Ca;f&&(ja[Ca]=f);var l={s:c,f:h,c:f?Ca:0,a:Array.prototype.slice.call(arguments,3),t:S[a],l:!!ka[a]},q;t:if("bidir"===wh||"c2p"===wh&&".."===a||"p2c"===wh&&".."!==a){q=window.location.href;var t="?";if("query"===nk)t="#";else if("hash"===nk)break t;t=q.lastIndexOf(t);t=-1===t?q.length:t;q=q.substring(0,
t)}else q=null;q&&(l.r=q);if(".."===a||null!=b(a)||window.document.getElementById(a))(q=Ya[a])||null===b(a)||(q=fc),0===c.indexOf("legacy__")&&(q=fc,l.s=c.substring(8),l.c=l.c?l.c:Ca),l.g=!0,l.r=h,q?(ka[a]&&(q=Qb.pg),!1===q.call(a,h,l)&&(Ya[a]=te,fc.call(a,h,l))):If[a]?If[a].push(l):If[a]=[l]},Rk:v,Xg:w,Wg:A,tf:E,Wd:function(a){return S[a]},mj:function(a){delete U[a];delete ka[a];delete S[a];delete rw[a];delete Ya[a]},Qk:function(){return fc.Kk()},ym:function(a,c){4<a.length?fc.Vo(a,h):g.apply(null,
a.concat(c))},zm:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){h(a)},0)},Pq:l,$d:function(a){var c=null,c=v(a);c||(c=(c=b(a))?c.origin:".."==a?Ta.parent:window.document.getElementById(a).src);return l(c)},gb:function(){!1===fc.gb(h,c)&&(fc=te);Yw?E(".."):_.Pb.Q("rpc",null,function(a){a=a.rpc||{};F(a);z(a)})},dk:q,Uo:b,B:"__ack",lh:ok||"..",M:0,ha:1,G:2}}();_.T.gb()};
_.T.Ca({Mm:function(a){throw Error("m`"+a);}});_.Fc=_.ke;(0,_.d)("gadgets.rpc.config",_.T.Ca);(0,_.d)("gadgets.rpc.register",_.T.Q);(0,_.d)("gadgets.rpc.unregister",_.T.Jd);(0,_.d)("gadgets.rpc.registerDefault",_.T.Am);(0,_.d)("gadgets.rpc.unregisterDefault",_.T.aB);(0,_.d)("gadgets.rpc.forceParentVerifiable",_.T.Fk);(0,_.d)("gadgets.rpc.call",_.T.call);(0,_.d)("gadgets.rpc.getRelayUrl",_.T.Rk);(0,_.d)("gadgets.rpc.setRelayUrl",_.T.Xg);(0,_.d)("gadgets.rpc.setAuthToken",_.T.Wg);(0,_.d)("gadgets.rpc.setupReceiver",_.T.tf);
(0,_.d)("gadgets.rpc.getAuthToken",_.T.Wd);(0,_.d)("gadgets.rpc.removeReceiver",_.T.mj);(0,_.d)("gadgets.rpc.getRelayChannel",_.T.Qk);(0,_.d)("gadgets.rpc.receive",_.T.ym);(0,_.d)("gadgets.rpc.receiveSameDomain",_.T.zm);(0,_.d)("gadgets.rpc.getOrigin",_.T.Pq);(0,_.d)("gadgets.rpc.getTargetOrigin",_.T.$d);

_.R=_.R||{};_.R.Ee=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.Lb)("cannot attachBrowserEvent: "+c)};_.R.Vr=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.Lb)("cannot removeBrowserEvent: "+c)};

_.Tb=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=v=0}function c(a){for(var c=b,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;a=h[0];for(var g=h[1],l=h[2],q=h[3],t=h[4],v,w,f=0;80>f;f++)40>f?20>f?(v=q^g&(l^q),w=1518500249):(v=g^l^q,w=1859775393):60>f?(v=g&l|q&(g|l),w=2400959708):(v=g^l^q,w=3395469782),v=((a<<5|a>>>27)&4294967295)+
v+t+w+c[f]&4294967295,t=q,q=l,l=(g<<30|g>>>2)&4294967295,g=a,a=v;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,b=a.length;h<b;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==v)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(l[v++]=a[g++],w++,64==v)for(v=0,c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}
function g(){var a=[],g=8*w;56>v?f(q,56-v):f(q,64-(v-56));for(var b=63;56<=b;b--)l[b]=g&255,g>>>=8;c(l);for(b=g=0;5>b;b++)for(var t=24;0<=t;t-=8)a[g++]=h[b]>>t&255;return a}for(var h=[],l=[],b=[],q=[128],t=1;64>t;++t)q[t]=0;var v,w;a();return{reset:a,update:f,xk:g,Of:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

_.Vb=function(){function a(c){c=c||window.event;var f=c.screenX+c.clientX<<16,f=f+(c.screenY+c.clientY),f=(new Date).getTime()%1E6*f;b=b*f%q;0<g&&++h==g&&_.R.Vr(window,"mousemove",a,!1)}function c(a){var c=(0,_.Tb)();c.update(a);return c.Of()}var f=window.crypto;if(f&&"function"==typeof f.getRandomValues)return function(){var a=new window.Uint32Array(1);f.getRandomValues(a);return Number("0."+a[0])};var g=(0,_.P)("random/maxObserveMousemove");null==g&&(g=-1);var h=0,l=Math.random(),b=1,q=1E6*(window.screen.width*
window.screen.width+window.screen.height);0!=g&&_.R.Ee(window,"mousemove",a,!1);var t=c(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+l);return function(){var a=b,a=a+(0,window.parseInt)(t.substr(0,20),16);t=c(t);return a/(q+Math.pow(16,20))}}();
(0,_.d)("shindig.random",_.Vb);
_.Sb=window.iframer={};_.V={};
_.V.ip=function(a,c,f){var g=Array.prototype.slice.call(arguments);_.V.Pk(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.T.call.apply(_.T,g))})};_.V.Sr=function(a,c){_.T.Q(a,c)};
_.Xb=function(a,c,f){a=String(a);if(null!=((0,_.Ua)(a,"authuser")||null)||null!=((0,_.Ua)(a,"hd")||null))return a;c=(0,_.ak)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var l=h[1],b=h[4],q=h[5];h[3]=="/"+f&&(g=(l||"")+(b||"/")+(q||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return l=h[2],a=h[4]||h[5],q=h[6],null!=c&&(g=(l||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+(q||
"")),g}f=null==c?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")}; _.google.ko=_.Xb;_.google.mr=_.ak;_.google.vN=_.vk;_.google.wN=_.ol;

_.V.J=_.V.J||{};_.V.J.jp=function(a){try{return!!a.document}catch(c){}return!1};_.V.J.Uk=function(a){var c=a.parent;return a!=c&&_.V.J.jp(c)?_.V.J.Uk(c):a};_.V.J.St=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};

var Zb=function(a){_.V.Rg[a]||(_.V.Rg[a]={},_.T.Q(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{}||g in{})){var h=this.callback,l=_.V.Rg[a][g],b;l&&Object.hasOwnProperty.call(l,c)?b=l[c]:Object.hasOwnProperty.call(_.V.Xw,a)&&(b=_.V.Xw[a]);if(b)return g=Array.prototype.slice.call(arguments,1),b._iframe_wrapped_rpc_&&h&&g.push(h),b.apply({},g)}(0,_.sa)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));return null}));
return _.V.Rg[a]};var $b=function(a,c,f){function g(g){var l=Array.prototype.slice.call(arguments,0),b=l[l.length-1];if("function"===typeof b){var q=b;l.pop()}l.unshift(c,a,q,f);_.T.call.apply(_.T,l)}g._iframe_wrapped_rpc_=!0;return g};var ac=function(){window.setTimeout(function(){_.T.call("..","_noop_echo",_.V.Lr)},0)};var bc=function(){_.T.Q("_noop_echo",function(){this.callback(_.V.rI(_.V.Uc[this.f]))})};_.dc=function(){return _.Ia.location.origin||_.Ia.location.protocol+"//"+_.Ia.location.host};
var ec=function(a){var c=(0,_.Ua)(a.location.href,"urlindex");if(c=(0,_.N)(_.Hb,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};var gc=function(){_.V.Kl++;return["I",_.V.Kl,"_",(new Date).getTime()].join("")};var ic=function(a){return a instanceof Array?a.join(","):a instanceof Object?_.Kb.stringify(a):a};var lc=function(){};var oc=function(a){a&&a.match(pc)&&(0,_.Fa)("googleapis.config/gcv",a)};var qc=function(a){_.Rb.xh.ys(a)};var rc=function(a){_.Rb.xh.pj(a)};
_.sc=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);return f};_.tc=function(a,c,f,g,h){var l=[],b;for(b in a)if(a.hasOwnProperty(b)){var q=c,t=f,v=a[b],w=g,A=Zb(b);A[q]=A[q]||{};w=_.R.Dg(w,v);v._iframe_wrapped_rpc_&&(w._iframe_wrapped_rpc_=!0);A[q][t]=w;l.push(b)}if(h)for(b in _.V.Xw)_.V.Xw.hasOwnProperty(b)&&l.push(b);return l.join(",")};var uc=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var l=a[h];g[l]=$b(l,c,f)}}return g};
var vc=function(a){return a&&a.disableMultiLevelParentRelay?!1:_.Sb&&_.Sb._open&&"inline"!=a.style&&!0!==a.inline&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};
var eo=function(a,c){var f={},g=c.params||{},h;for(h in a)"#"==h.charAt(0)&&(f[h.substring(1)]=a[h]),0==h.indexOf("fr-")&&(f[h.substring(3)]=a[h]),"#"==g[h]&&(f[h]=a[h]);for(var l in f)delete a["fr-"+l],delete a["#"+l],delete a[l];return f};var xc=function(a){if(":"==a.charAt(0)){var c=(0,_.P)("iframes/"+a.substring(1));a={};(0,_.Ra)(c,a);(c=a.url)&&(a.url=(0,_.mc)(c));a.params||(a.params={});return a}return{url:(0,_.mc)(a)}};
var yc=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};
var zc=function(a,c,f,g,h,l,b,q){this.Ca=xc(a);this.openParams=this.Fz=c;this.Ya=f||{};this.Oa=g;this.Qz=!1;Ac(this,c.style);this.my={};Bc(this,function(){var a;(a=this.Fz.style)&&_.V.yf[a]?a=_.V.yf[a]:a?((0,_.Lb)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=Cc;if(a){var c;if("function"===typeof a)c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.R.Dg(a,g,this):g}c=f}for(var b in h)a=c[b],"function"===typeof a&&Dc(this,h[b],
_.R.Dg(c,a))}l&&Dc(this,"close",l)});this.ya=this.ac=b;this.dj=(q||[]).slice();b&&this.dj.unshift(b.Hh())};var Ac=function(a,c){if(!a.Qz){var f=c&&!_.V.yf[c]&&_.V.Ih[c];f?(a.BA=[],f(function(){a.Qz=!0;for(var c=0,f=a.BA.length;c<f;++c)a.BA[c].call(a)})):a.Qz=!0}};var Bc=function(a,c){a.Qz?c.call(a):a.BA.push(c)};var Dc=function(a,c,f){a.my[c]=a.my[c]||[];a.my[c].push(f)};var Ec=function(a,c){return"number"==typeof c?{value:c,od:c+"px"}:"100%"==c?{value:100,od:"100%",Ul:!0}:null};
var Gc=function(a,c,f,g,h,l,b){zc.call(this,a,c,f,g,Hc,h,l,b);this.id=c.id||gc();this.G=c.rpcToken||Math.round(1E9*(0,_.Vb)());this.M=eo(this.Ya,this.Ca);this.XA={};Bc(this,function(){this.Pb("open");(0,_.sc)(this.XA,this)})};
var Ic=function(a,c,f,g,h,l,b){zc.call(this,a,c,f,g,Jc,h,l,b);this.url=a;this.B=null;this.VB=gc();Bc(this,function(){this.Pb("beforeparentopen");var a=(0,_.sc)(this.Oa);a._onopen=this.NJ;a._ready=this.Jg;a._onclose=this.MJ;this.Ya._methods=(0,_.tc)(a,"..",this.VB,this,!0);var a={},c;for(c in this.Ya)a[c]=ic(this.Ya[c]);var f=this.Ca.url;if(this.Fz.hideUrlFromParent){c=window.name;var g=f,f=(0,_.db)(this.Ca.url,this.Ya,{},ic),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=
h["#urlindex"];a["#opener"]&&void 0!=h["#urlindex"]?(a["#opener"]=c+","+a["#opener"],c={url:g,Ya:a}):(g=(0,_.N)(_.Hb,"fUrl",[]),h=g.length,g[h]=f,_.Hb.rUrl=ec,a["#opener"]=c,a["#urlindex"]=h,c=_.Rb.Pq(_.Ia.location.href),f=(0,_.P)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,Ya:a});f=c.url;a=c.Ya}_.Sb._open({url:f,openParams:this.Fz,params:a,proxyId:this.VB,openedByProxyChain:this.dj})})};
var Kc=function(a,c,f,g,h,l,b){zc.call(this,a,c,f,g,Jc,l,b);this.id=c.id||gc();this.G=h;g._close=this.close;this.onClosed=this.B;this.JF=0;Bc(this,function(){this.Pb("beforeparentopen");var c=(0,_.sc)(this.Oa);this.Ya._methods=(0,_.tc)(c,"..",this.VB,this,!0);c={};c.queryParams=this.Ya;a=(0,_.qa)(_.Ja,this.Ca.url,this.id,c);var f=h.pm(a);this.canAutoClose=function(a){a(h.ok(f))};h.Tm(f,this);this.JF=f})};var Mc=function(a){return _.V.yf[a]};var Nc=function(a,c){_.V.yf[a]=c}; var Oc=function(a){a=a||{};"auto"===a.height&&(a.height=_.Ob.ih());var c=window&&Pc&&Pc.ma();c?c.Gm(a.width||0,a.height||0):_.Sb&&_.Sb._resizeMe&&_.Sb._resizeMe(a)};var Qc=function(a){oc(a)};
if(window.ToolbarApi)Pc=window.ToolbarApi,Pc.ma=window.ToolbarApi.getInstance,Pc.prototype=window.ToolbarApi.prototype,_.k=Pc.prototype,_.k.pm=Pc.prototype.openWindow,_.k.rk=Pc.prototype.closeWindow,_.k.Tm=Pc.prototype.setOnCloseHandler,_.k.ok=Pc.prototype.canClosePopup,_.k.Gm=Pc.prototype.resizeWindow;else{var Rc=null,Pc=function(){};Pc.ma=function(){!Rc&&window.external&&window.external.GTB_IsToolbar&&(Rc=new Pc);return Rc};_.k=Pc.prototype;_.k.pm=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.k.rk=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.k.Tm=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.k.ok=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.k.Gm=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=Pc;window.ToolbarApi.getInstance=Pc.ma};
var pc=/^[-_.0-9A-Za-z]+$/,Hc={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},Jc={onBeforeParentOpen:"beforeparentopen"},Cc={onOpen:function(a){var c=a.va();a.Pa(c.container||c.element);return a},onClose:function(a){a.remove()}};_.V.Wp=function(a){var c=(0,_.O)();(0,_.Ra)(_.vb,c);(0,_.Ra)(a,c);return c};_.k=zc.prototype;_.k.va=function(){return this.Fz};_.k.tb=function(){return this.Ya};
_.k.bi=function(){return this.Oa};_.k.ci=function(){return this.ya};_.k.ea=function(a,c){Bc(this,function(){Dc(this,a,c)})};_.k.Ub=function(a,c){Bc(this,function(){var f=this.my[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};_.k.Pb=function(a,c){var f,g=this.my[a];if(g)for(var h=Array.prototype.slice.call(arguments,1),l=0,b=g.length;l<b;++l)try{f=g[l].apply({},h)}catch(q){(0,_.sa)(['Exception when calling callback "',a,'" with exception "',q.name,": ",q.message,'".'].join(""))}return f};
yc(Gc,zc);_.k=Gc.prototype;
_.k.Pa=function(a,c){if(!this.Ca.url)return(0,_.sa)("Cannot open iframe, empty URL."),this;var f=this.id;_.V.Uc[f]=this;var g=(0,_.sc)(this.Oa);g._ready=this.Jg;g._close=this.close;g._open=this.rm;g._resizeMe=this.Ug;g._renderstart=this.PA;var h=this.M;this.G&&(h.rpctoken=this.G);h._methods=(0,_.tc)(g,f,"",this,!0);this.ha=a="string"===typeof a?window.document.getElementById(a):a;g={};g.id=f;if(c){g.attributes=c;var l=c.style;if("string"===typeof l){var b;if(l){b=[];for(var l=l.split(";"),q=0,t=l.length;q<
t;++q){var v=l[q];if(0!=v.length||q+1!=t)v=v.split(":"),2==v.length&&v[0].match(/^[ a-zA-Z_-]+$/)&&v[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?b.push(v.join(":")):(0,_.sa)(['Iframe style "',l[q],'" not allowed.'].join(""))}b=b.join(";")}else b="";c.style=b}}this.va().allowPost&&(g.allowPost=!0);g.queryParams=this.Ya;g.fragmentParams=h;g.paramsSerializer=ic;this.B=(0,_.tb)(this.Ca.url,a,g);h=this.B.getAttribute("data-postorigin")||this.B.src;_.V.Uc[f]=this;_.T.Wg(this.id,this.G);_.T.Xg(this.id,h);return this};
_.k.Cg=function(a,c){this.XA[a]=c};_.k.Hh=function(){return this.id};_.k.Mc=function(){return this.B};_.k.V=function(){return this.ha};_.k.qc=function(a){this.ha=a};_.k.Jg=function(a){var c=uc(a,this.id,"");this.ya&&"function"==typeof this.Oa._ready&&(a._methods=(0,_.tc)(c,this.ya.Hh(),this.id,this,!1),this.Oa._ready(a));(0,_.sc)(a,this);(0,_.sc)(c,this);this.Pb("ready",a)};_.k.PA=function(a){this.Pb("renderstart",a)};_.k.close=function(a){a=this.Pb("close",a);delete _.V.Uc[this.id];return a};
_.k.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.k.rm=function(a){var c=uc(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.ha);if(vc(a.openParams))new Ic(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new Gc(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;Bc(f,function(){var a={childId:f.Hh()},l=f.XA;l._toclose=f.close;a._methods=(0,_.tc)(l,g.id,f.id,f,!1);c._onopen(a)})}};
_.k.Ug=function(a){if(void 0===this.Pb("resize",a)&&this.B){var c=Ec(this,a.width);null!=c&&(this.B.style.width=c.od);a=Ec(this,a.height);null!=a&&(this.B.style.height=a.od);this.B.parentElement&&(null!=c&&c.Ul||null!=a&&a.Ul)&&(this.B.parentElement.style.display="block")}};yc(Ic,zc);Ic.prototype.G=function(){return this.B};
Ic.prototype.NJ=function(a){this.B=a.childId;var c=uc(a,"..",this.B);(0,_.sc)(c,this);this.close=c._toclose;_.V.Uc[this.B]=this;this.ya&&this.Oa._onopen&&(a._methods=(0,_.tc)(c,this.ya.Hh(),this.B,this,!1),this.Oa._onopen(a))};Ic.prototype.Jg=function(a){var c=String(this.B),f=uc(a,"..",c);(0,_.sc)(a,this);(0,_.sc)(f,this);this.Pb("ready",a);this.ya&&this.Oa._ready&&(a._methods=(0,_.tc)(f,this.ya.Hh(),c,this,!1),this.Oa._ready(a))};
Ic.prototype.MJ=function(a){if(this.ya&&this.Oa._onclose)this.Oa._onclose(a);else return a=this.Pb("close",a),delete _.V.Uc[this.B],a};yc(Kc,zc);Kc.prototype.close=function(a){a=this.Pb("close",a);this.G.rk(this.JF);return a};Kc.prototype.B=function(){this.Pb("close")};
(function(){_.V.Uc={};_.V.yf={};_.V.Ih={};_.V.Kl=0;_.V.Rg={};_.V.Xw={};_.V.Ng=null;_.V.Mg=[];_.V.Lr=function(a){var c=!1;try{if(null!=a)var h=window.parent.frames[a.id],c=h.iframer.id==a.id&&h.iframes.openedId_(_.Sb.id)}catch(l){}try{_.V.Ng={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.V.Mg.length;++a)_.V.Mg[a](_.V.Ng);_.V.Mg=[]}catch(b){}};_.V.rI=function(a){var c=a&&a.ya,h=null;c&&(h={},h.id=c.Hh(),h.proxyChain=
a.dj);return h};bc();if(window.parent!=window){var a=_.R.$c();a.gcv&&oc(a.gcv);var c=a.jsh;c&&qc(c);(0,_.sc)(uc(a,"..",""),_.Sb);(0,_.sc)(a,_.Sb);ac()}_.V.Cr=Mc;_.V.na=Nc;_.V.xs=Qc;_.V.resize=Oc;_.V.Rp=function(a){return _.V.Ih[a]};_.V.qj=function(a,c){_.V.Ih[a]=c};_.V.rD=Oc;_.V.Ds=Qc;_.V.ng={};_.V.ng.get=Mc;_.V.ng.set=Nc;_.V.Zo=function(a,c){Zb(a);_.V.Xw[a]=c||window[a]};_.V.Mt=function(a){delete _.V.Xw[a]};_.V.open=function(a,c,h,l,b,q){3==arguments.length?l={}:4==arguments.length&&"function"===
typeof l&&(b=l,l={});var t="bubble"===c.style&&Pc&&Pc.ma();return t?new Kc(a,c,h,l,t,b,q):vc(c)?new Ic(a,c,h,l,b,q):new Gc(a,c,h,l,b,q)};_.V.close=function(a,c){_.Sb&&_.Sb._close&&_.Sb._close(a,c)};_.V.Tb=function(a,c,h){2==arguments.length&&"function"===typeof c&&(h=c,c={});var l=a||{};"height"in l||(l.height=_.Ob.ih());l._methods=(0,_.tc)(c||{},"..","",_.Sb,!0);_.Sb&&_.Sb._ready&&_.Sb._ready(l,h)};_.V.Pk=function(a){_.V.Ng?a(_.V.Ng):_.V.Mg.push(a)};_.V.Ir=function(a){return!!_.V.Uc[a]};_.V.Vp=function(){return["https://ssl.gstatic.com/gb/js/",
(0,_.P)("googleapis.config/gcv")].join("")};_.V.Qr=function(a){var c={mouseover:1,mouseout:1};if(_.Sb._event)for(var h=0;h<a.length;h++){var l=a[h];l in c&&_.R.Ee(window.document,l,function(a){_.Sb._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.V.zs=qc;_.V.pj=rc;_.V.kr=lc;_.V.$q=_.Sb})();
(0,_.d)("iframes.allow",_.V.Zo);(0,_.d)("iframes.callSiblingOpener",_.V.ip);(0,_.d)("iframes.registerForOpenedSibling",_.V.Sr);(0,_.d)("iframes.close",_.V.close);(0,_.d)("iframes.getGoogleConnectJsUri",_.V.Vp);(0,_.d)("iframes.getHandler",_.V.Cr);(0,_.d)("iframes.getDeferredHandler",_.V.Rp);(0,_.d)("iframes.getParentInfo",_.V.Pk);(0,_.d)("iframes.iframer",_.V.$q);(0,_.d)("iframes.open",_.V.open);(0,_.d)("iframes.openedId_",_.V.Ir);(0,_.d)("iframes.propagate",_.V.Qr);(0,_.d)("iframes.ready",_.V.Tb);
(0,_.d)("iframes.resize",_.V.resize);(0,_.d)("iframes.setGoogleConnectJsVersion",_.V.xs);(0,_.d)("iframes.setBootstrapHint",_.V.pj);(0,_.d)("iframes.setJsHint",_.V.zs);(0,_.d)("iframes.setHandler",_.V.na);(0,_.d)("iframes.setDeferredHandler",_.V.qj);(0,_.d)("IframeBase",zc);(0,_.d)("IframeBase.prototype.addCallback",zc.prototype.ea);(0,_.d)("IframeBase.prototype.getMethods",zc.prototype.bi);(0,_.d)("IframeBase.prototype.getOpenerIframe",zc.prototype.ci);
(0,_.d)("IframeBase.prototype.getOpenParams",zc.prototype.va);(0,_.d)("IframeBase.prototype.getParams",zc.prototype.tb);(0,_.d)("IframeBase.prototype.removeCallback",zc.prototype.Ub);(0,_.d)("Iframe",Gc);(0,_.d)("Iframe.prototype.close",Gc.prototype.close);(0,_.d)("Iframe.prototype.exposeMethod",Gc.prototype.Cg);(0,_.d)("Iframe.prototype.getId",Gc.prototype.Hh);(0,_.d)("Iframe.prototype.getIframeEl",Gc.prototype.Mc);(0,_.d)("Iframe.prototype.getSiteEl",Gc.prototype.V);
(0,_.d)("Iframe.prototype.openInto",Gc.prototype.Pa);(0,_.d)("Iframe.prototype.remove",Gc.prototype.remove);(0,_.d)("Iframe.prototype.setSiteEl",Gc.prototype.qc);(0,_.d)("Iframe.prototype.addCallback",Gc.prototype.ea);(0,_.d)("Iframe.prototype.getMethods",Gc.prototype.bi);(0,_.d)("Iframe.prototype.getOpenerIframe",Gc.prototype.ci);(0,_.d)("Iframe.prototype.getOpenParams",Gc.prototype.va);(0,_.d)("Iframe.prototype.getParams",Gc.prototype.tb);(0,_.d)("Iframe.prototype.removeCallback",Gc.prototype.Ub);
(0,_.d)("IframeProxy",Ic);(0,_.d)("IframeProxy.prototype.getTargetIframeId",Ic.prototype.G);(0,_.d)("IframeProxy.prototype.addCallback",Ic.prototype.ea);(0,_.d)("IframeProxy.prototype.getMethods",Ic.prototype.bi);(0,_.d)("IframeProxy.prototype.getOpenerIframe",Ic.prototype.ci);(0,_.d)("IframeProxy.prototype.getOpenParams",Ic.prototype.va);(0,_.d)("IframeProxy.prototype.getParams",Ic.prototype.tb);(0,_.d)("IframeProxy.prototype.removeCallback",Ic.prototype.Ub);(0,_.d)("IframeWindow",Kc);
(0,_.d)("IframeWindow.prototype.close",Kc.prototype.close);(0,_.d)("IframeWindow.prototype.onClosed",Kc.prototype.B);(0,_.d)("iframes.util.getTopMostAccessibleWindow",_.V.J.Uk);(0,_.d)("iframes.handlers.get",_.V.ng.get);(0,_.d)("iframes.handlers.set",_.V.ng.set);(0,_.d)("iframes.resizeMe",_.V.rD);(0,_.d)("iframes.setVersionOverride",_.V.Ds);
zc.prototype.send=function(a,c,f){_.V.Gr(this,a,c,f)};_.Sb.send=function(a,c,f){_.V.Gr(_.Sb,a,c,f)};zc.prototype.Q=function(a,c){var f=this;f.ea(a,function(a){c.call(f,a)})};_.V.Gr=function(a,c,f,g){var h=[];void 0!==f&&h.push(f);g&&h.push(function(a){g.call(this,[a])});a[c]&&a[c].apply(a,h)};_.V.Fa=function(){return!0};(0,_.d)("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.V.Fa);(0,_.d)("IframeBase.prototype.send",zc.prototype.send);(0,_.d)("IframeBase.prototype.register",zc.prototype.Q);
(0,_.d)("Iframe.prototype.send",Gc.prototype.send);(0,_.d)("Iframe.prototype.register",Gc.prototype.Q);(0,_.d)("IframeProxy.prototype.send",Ic.prototype.send);(0,_.d)("IframeProxy.prototype.register",Ic.prototype.Q);(0,_.d)("IframeWindow.prototype.send",Kc.prototype.send);(0,_.d)("IframeWindow.prototype.register",Kc.prototype.Q);(0,_.d)("iframes.iframer.send",_.V.$q.send);

var Uc=function(a,c){var f=_.Tc[a];f&&f.state<c&&(f.state=c)};var Vc=function(a){a=(a=_.Tc[a])?a.oid:void 0;if(a){var c=_.Ja.getElementById(a);c&&c.parentNode.removeChild(c);delete _.Tc[a];Vc(a)}};_.bf=function(a){a=a.container;"string"===typeof a&&(a=window.document.getElementById(a));return a};_.gf=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.hf=function(a,c){var f={},g=a.va(),h=c&&c.width,l=c&&c.height,b=c&&c.verticalAlign;b&&(f.verticalAlign=b);h||(h=g.width||a.width);l||(l=g.height||a.height);g.width=f.width=h;g.height=f.height=l;g=a.Mc();h=a.Hh();Uc(h,2);t:{h=a.V();f=f||{};if((0,_.me)()){var q=g.id;if(q){l=(l=_.Tc[q])?l.state:void 0;if(1===l||4===l)break t;Vc(q)}}(l=h.nextSibling)&&l.getAttribute&&l.getAttribute("data-gapistub")&&(h.parentNode.removeChild(l),h.style.cssText="");var l=f.width,b=f.height,t=h.style;t.textIndent="0";
t.margin="0";t.padding="0";t.background="transparent";t.borderStyle="none";t.cssFloat="none";t.styleFloat="none";t.lineHeight="normal";t.fontSize="1px";t.verticalAlign="baseline";h=h.style;h.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";l&&(h.width=g.width=l+"px");b&&(h.height=g.height=b+"px");f.verticalAlign&&(h.verticalAlign=f.verticalAlign);q&&Uc(q,3)}(q=c?c.title:null)&&a.Mc().setAttribute("title",q)};_.jf=function(a){var c=a.V();c&&c.removeChild(a.Mc())};
_.Ww=function(a){function c(a){(0,_.hf)(this,a)}a.where=(0,_.bf)(a);var f=a.messageHandlers=a.messageHandlers||{};f._ready=c;f._renderstart=c;var g=a.onClose;a.onClose=function(a){g&&g.call(this,a);(0,_.jf)(this)};a.onCreate=function(a){var c=a.Mc();c.style.cssText=(0,_.gf)(c,a)}};
_.Tc=(0,_.N)(_.Hb,"rw",(0,_.O)());
var Xw={open:function(a){var c=(0,_.bf)(a.va());return a.Pa(c,{style:(0,_.gf)(c,a)})},attach:function(a,c){var f=(0,_.bf)(a.va()),g=c.id,h=c.getAttribute("data-postorigin")||c.src,l=/#(?:.*&)?rpctoken=(\d+)/.exec(h),l=l&&l[1];a.id=g;a.G=l;a.ha=f;a.B=c;_.V.Uc[g]=a;l=(0,_.sc)(a.Oa);l._ready=a.Jg;l._close=a.close;l._open=a.rm;l._resizeMe=a.Ug;l._renderstart=a.PA;(0,_.tc)(l,g,"",a,!0);_.T.Wg(a.id,a.G);_.T.Xg(a.id,h);var f=_.V.Wp({style:(0,_.gf)(f,a)}),b;for(b in f)Object.prototype.hasOwnProperty.call(f, b)&&("style"==b?a.B.style.cssText=f[b]:a.B.setAttribute(b,f[b]))}};Xw.onready=_.hf;Xw.onRenderStart=_.hf;Xw.close=_.jf;_.V.na("inline",Xw);


_.Sl=function(a,c){return 0==a.lastIndexOf(c,0)};_.ne=2147483648*Math.random()|0;
_.Xc=function(a){var c;a.match(/^https?%3A/i)&&(c=(0,window.decodeURIComponent)(a));a=c?c:a;return(0,_.ua)(window.document,a)};_.Yc=function(a){a=a||"canonical";for(var c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],l=h.getAttribute("rel");if(l&&l.toLowerCase()==a&&(h=h.getAttribute("href"))&&(h=(0,_.Xc)(h))&&null!=h.match(/^https?:\/\/[\w\-\_\.]+/i))return h}return window.location.href};_.Zc=function(a,c,f,g){return(a="string"==typeof a?a:void 0)?(0,_.Xc)(a):(0,_.Yc)(g)};
var $c=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};var ad=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return String(c)};var bd=function(a){if($c(a))return"true"};_.cd=function(a){return"string"==typeof a&&_.dd[a.toLowerCase()]?a.toLowerCase():"standard"};_.ed=function(a,c){return"tall"==(0,_.cd)(c)?"true":null==a||$c(a)?"true":"false"};_.fd=function(a,c,f){null==a&&f&&(a=f.db,null==a&&(a=f.gwidget&&f.gwidget.db));return a||void 0};
_.gd=function(a,c,f){null==a&&f&&(a=f.ecp,null==a&&(a=f.gwidget&&f.gwidget.ecp));return a||void 0};_.dd={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.hd={href:[_.Zc,"url"],width:[ad],size:[_.cd],resize:[bd],autosize:[bd],count:[function(a,c){return(0,_.ed)(c.count,c.size)}],db:[_.fd],ecp:[_.gd],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[bd],recommendations:[],fu:[],ad:[bd],cr:[ad],ag:[ad],"fr-ai":[],"fr-sigh":[]};

_.Zw=function(a){var c=window;a=(a||c.location.href).match(/.*(\?|#|&)usegapi=([^&#]+)/)||[];return"1"===(0,window.decodeURIComponent)(a[a.length-1]||"")};
_.md=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};var $w=function(a){var c=(0,_.N)(_.Hb,"sws",[]);return 0<=_.Nb.call(c,a)};_.ld=function(a,c,f){return(0,_.Zc)(a,c,f,c.action?void 0:"publisher")};
var ax=function(){if(!bx){for(var a=window.document.getElementsByTagName("meta"),c=0;c<a.length;++c){var f=a[c].name.toLowerCase();if((0,_.Sl)(f,"google-signin-")){var f=f.substring(14),g=a[c].content;cx[f]&&g&&(dx[f]=g)}}if(window.self!==window.top){var a=window.document.location.toString(),h;for(h in cx)0<cx[h]&&(c=(0,_.Ua)(a,h,""))&&(dx[h]=c)}bx=!0}h=(0,_.O)();(0,_.Ra)(dx,h);return h};
var ex=function(a){for(var c=(0,_.O)(),f=0!=a.nodeName.toLowerCase().indexOf("g:"),g=0,h=a.attributes.length;g<h;g++){var l=a.attributes[g],b=l.name,q=l.value;0<=_.Nb.call(Gd,b)||f&&0!=b.indexOf("data-")||"null"===q||"specified"in l&&!l.specified||(f&&(b=b.substr(5)),c[b.toLowerCase()]=q)}a=a.style;(f=nd(a&&a.height))&&(c.height=String(f));(a=nd(a&&a.width))&&(c.width=String(a));return c};
_.fx=function(a,c,f,g,h,l){var b;f.rd?b=c:(b=window.document.createElement("div"),c.setAttribute("data-gapistub",!0),b.style.cssText="position:absolute;width:450px;left:-10000px;",c.parentNode.insertBefore(b,c));l.siteElement=b;b.id||(b.id=(0,_.lf)(a));c=(0,_.O)();c[">type"]=a;(0,_.Ra)(f,c);a=(0,_.tb)(g,b,h);l.iframeNode=a;l.id=a.getAttribute("id")};_.lf=function(a){(0,_.N)(id,a,0);return"___"+a+"_"+id[a]++};
var nd=function(a){var c=void 0;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};
var xd=function(a,c){t:{yd.ps0=(new Date).getTime();Ad("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.Ja,g;g=_.Ja.documentMode;if(f.querySelectorAll&&(!g||8<g)){g=c?[c]:(0,_.wd)(Bd).concat((0,_.wd)(Cd)).concat((0,_.wd)(Dd));for(var h=[],l=0;l<g.length;l++){var b=g[l];h.push(".g-"+b,"g\\:"+b)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.O)();for(h=0;h<g.length;h++){l=g[h];var q=l,b=c,t=q.nodeName.toLowerCase(),v=void 0;q.getAttribute("data-gapiscan")?
b=null:(0==t.indexOf("g:")?v=t.substr(2):(q=(q=String(q.className||q.getAttribute("class")))&&gx.exec(q))&&(v=q[1]),b=!v||!(Bd[v]||Cd[v]||Dd[v])||b&&v!==b?null:v);b&&(hx[b]||0==l.nodeName.toLowerCase().indexOf("g:")||0!=(0,_.wd)(ex(l)).length)&&(l.setAttribute("data-gapiscan",!0),(0,_.N)(f,b,[]).push(l))}for(var w in f)Fd.push(w);yd.ps1=(new Date).getTime();Ad("ps1");if(w=Fd.join(":"))try{_.Yi.load(w,void 0)}catch(A){(0,_.kd)(A);break t}var F,l=[];for(F in f)for(h=f[F],g=0,w=h.length;g<w;g++)b=h[g],
Hd(F,b,ex(b),l,w)}};var Id=function(a,c){var f=(0,_.N)(_.Hb,"watt",(0,_.O)())[a];c&&f?(f(c),(f=c.iframeNode)&&f.setAttribute("data-gapiattached",!0)):_.Yi.load(a,function(){var f=(0,_.N)(_.Hb,"watt",(0,_.O)())[a],h=c&&c.iframeNode;h&&f?(f(c),h.setAttribute("data-gapiattached",!0)):(0,_.Yi[a].go)(h&&h.parentNode)})};
var Hd=function(a,c,f,g,h,l){switch(Jd(c,a,l)){case 0:a=Dd[a]?a+"_annotation":a;g={};g.iframeNode=c;g.userParams=f;Id(a,g);break;case 1:if(c.parentNode){l=!0;f.dontclear&&(l=!1);delete f.dontclear;var b,q,t;q=t=a;"plus"==a&&f.action&&(t=a+"_"+f.action,q=a+"/"+f.action);(t=(0,_.P)("iframes/"+t+"/url"))||(t=":socialhost:/:session_prefix:_/widget/render/"+q);q=(0,_.mc)(t);var v="iframes/"+a+"/params/";t={};(0,_.Ra)(f,t);var w;(w=(w=(0,_.P)("lang")||(0,_.P)("gwidget/lang"))||ix[a]||(0,_.P)("hl/absent")?
w:"en-US")&&(t.hl=w);jx[a]||(t.origin=(0,_.md)());t.exp=(0,_.P)(v+"exp");if(v=(0,_.P)(v+"location"))for(w=0;w<v.length;w++){var A=v[w];t[A]=_.Ia.location[A]}switch(a){case "plus":case "follow":t.url=(0,_.ld)(t.href,f,null);delete t.href;break;case "plusone":t.url=f.href?(0,_.Xc)(f.href):(0,_.Yc)();t.db=(0,_.fd)(f.db,void 0,(0,_.P)());t.ecp=(0,_.gd)(f.ecp,void 0,(0,_.P)());delete t.href;break;case "signin":t.url=(0,_.Yc)()}_.Hb.ILI&&(t.iloader="1");delete t["data-onload"];delete t.rd;t.gsrc=(0,_.P)("iframes/:source:");
v=(0,_.P)("inline/css");"undefined"!==typeof v&&0<h&&v>=h&&(t.ic="1");v=/^#|^fr-/;h={};for(var F in t)(0,_.Qa)(t,F)&&v.test(F)&&(h[F.replace(v,"")]=t[F],delete t[F]);F="q"==(0,_.P)("iframes/"+a+"/params/si")?t:h;var v=ax(),z;for(z in v)!(0,_.Qa)(v,z)||(0,_.Qa)(t,z)||(0,_.Qa)(h,z)||(F[z]=v[z]);z=[].concat(Ld);F=(0,_.P)("iframes/"+a+"/methods");(0,_.jd)(F)&&(z=z.concat(F));for(b in f)(0,_.Qa)(f,b)&&/^on/.test(b)&&("plus"!=a||"onconnect"!=b)&&(z.push(b),delete t[b]);delete t.callback;h._methods=z.join(",");
b=(0,_.db)(q,t,h);z={allowPost:1,attributes:Md};z.dontclear=!l;l={};l.userParams=f;l.url=b;l.type=a;(0,_.fx)(a,c,f,b,z,l);c=l.id;f=(0,_.O)();f.id=c;f.userParams=l.userParams;f.url=l.url;f.type=l.type;f.state=1;_.Tc[c]=f;c=l}else c=null;c&&((f=c.id)&&g.push(f),Id(a,c))}};var Jd=function(a,c,f){if(a&&1===a.nodeType&&c){if(f)return 1;if(Dd[c]){if(Nd[a.nodeName.toLowerCase()])return(a=a.innerHTML)&&a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?0:1}else{if(Cd[c])return 0;if(Bd[c])return 1}}return null};
var Od=function(a,c,f,g){Pd[f]=Pd[f]||!!g;(0,_.N)(Qd,f,[]);Qd[f].push([a,c])};var Ad=function(a,c,f){var g=Rd.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};var Sd=function(a,c,f,g){if("_p"==c)throw Error("n`_p");nf(a,c,f,g)};var nf=function(a,c,f,g){Td(c,f)[a]=g||(new Date).getTime();Ad(a,c,f)};var Td=function(a,c){var f=(0,_.N)(Ud,a,(0,_.O)());return(0,_.N)(f,c,(0,_.O)())};var Vd=function(a,c,f){var g=null;c&&f&&(g=Td(c,f)[a]);return g||yd[a]};_.of=function(a,c){nf("waaf0",a,c)};
_.pf=function(a,c){nf("waaf1",a,c)};var Wd=function(a,c){this.type=a?"_p"==a?"m":"w":"g";this.name=a;this.B=c};var Xd=function(a){var c=[];c.push("l"+((0,_.P)("isPlusUser")?"1":"0"));var f="m"+(Yd?"1":"0");c.push(f);if("m"==a.type)c.push("p"+a.B);else if("w"==a.type){var g="n"+a.B;c.push(g);"0"==a.B&&c.push(f+g)}c.push("u"+((0,_.P)("isLoggedIn")?"1":"0"));return c};
var Zd=function(a,c,f){for(var g=new Wd(c,f),h=(0,_.N)($d,g.key(),(0,_.O)()),l=Qd[a]||[],b=0;b<l.length;++b){var q=l[b],t=h,v=q[0],w=a,A=c,F=f,q=Vd(q[1],A,F),w=Vd(w,A,F);t[v]=q&&w?w-q:null}Pd[a]&&ae&&(be(ce),be(g))};var de=function(a,c){c=c||[];for(var f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
var be=function(a){var c=_.Ia.__gapi_jstiming__;c.sn=ee[a.type];var f=new c.Timer(0),g;t:{switch(a.type){case "g":g="global";break t;case "m":g=a.B;break t;case "w":g=a.name;break t}g=void 0}f.name=g;g=!1;var h=a.key(),l=$d[h];f.tick("_start",null,0);for(var b in l)f.tick(b,"_start",l[b]),g=!0;$d[h]=(0,_.O)();if(g){b=[];g=(0,_.P)("lexps");b=b.concat(de("e",g));b=b.concat(de("",Xd(a)));for(h=0;h<fe.length;h++)l=fe[h],0<=_.Nb.call(g,l)&&(b=b.concat(de(l?"e"+l:"",Xd(a))));b=de("abc_",b);c.report(f,{e:b.join(",")})}};
var gg=function(a){return a};var Kg=function(a){var c=(0,_.P)(a);return"undefined"!==typeof c?c:(0,_.P)("gwidget/"+a)};var kx=function(){var a=this&&this.Hh();a&&(_.Hb.drw=a)};var lx=function(){_.Hb.drw=null};var Uj=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};var En=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:null};
var Ft=function(){return Kg("lang")||"en-US"};var It=function(a){if(!_.V.Cr("attach")){var c={},f=_.V.Cr("inline"),g;for(g in f)f.hasOwnProperty(g)&&(c[g]=f[g]);c.open=function(a){var c=window.document.getElementById(a.va().renderData.id);if(!c)throw Error("o");return f.attach(a,c)};_.V.na("attach",c)}a.style="attach"};
var Jt=function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[g.Xs]=1;g.nr=c}function f(a){for(var c in a)if((0,_.Qa)(a,c)){g.Ca[c]=[En];g.jd.push(c);var f=a[c],q=null,t=null,v=null;"function"===typeof f?q=f:f&&"object"===typeof f&&(q=f.Er,t=f.Kg,v=f.Qh);v&&(g.jd.push(v),g.Ca[v]=[En],g.Rh[c]=v);q&&(g.Ca[c]=[q]);t&&(g.Ie[c]=t)}}var g={};g.Fb=a[0];g.Kj=-1;g.tn="___"+g.Fb+"_";g.Xs="g:"+g.Fb;g.Wt="g-"+g.Fb;g.Dm=[];g.Ca={};g.jd=[];g.Rh={};g.Ie={};a[1]&&(g.Jr=a[1]);(function(a){g.Ca=
a;for(var c in Mt)Mt.hasOwnProperty(c)&&!g.Ca.hasOwnProperty(c)&&(g.Ca[c]=Mt[c])})(a[2]||{});a[3]&&f(a[3]);a[4]&&c(a[4]);a[5]&&(g.qe=a[5]);g.nu=!0===a[6];g.Or=a[7];g.bL=a[8];g.nr||c(Rt);g.bj=function(a){g.Kj++;Sd("wrs",g.Fb,String(g.Kj));var c=[],f=a.element,q=a.Ca,t=":"+g.Fb;":plus"==t&&a.pe&&a.pe.action&&(t+="_"+a.pe.action);var v=St(g,q),w={};(0,_.Ra)(ax(),w);for(var A in a.pe)null!=a.pe[A]&&(w[A]=a.pe[A]);A={container:f.id,renderData:a.Xr,style:"inline",height:q.height,width:q.width};It(A);g.qe&&
(c[2]=A,c[3]=w,c[4]=v,g.qe("i",c));t=_.V.open(t,A,w,v);a=a.xp;Tt(t,q);Ut(t,f);sw(g,t,a);c[5]=t;g.qe&&g.qe("e",c)};return g};var St=function(a,c){for(var f={},g=a.jd.length-1;0<=g;--g){var h=a.jd[g],l=c[a.Rh[h]||h]||c[h],b=c[h];b&&l!==b&&(l=function(a,c){return function(f){c.apply(this,arguments);a.apply(this,arguments)}}(l,b));l&&(f[h]=l)}for(var q in a.Ie)a.Ie.hasOwnProperty(q)&&(f[q]=tw(f[q]||function(){},a.Ie[q]));f.drefresh=kx;f.erefresh=lx;return f};
var tw=function(a,c){return function(f){var g=c(f);if(g){var h=f.href||null;if(zx){if(window._gat)try{var l=window._gat._getTrackerByName("~0");l&&"UA-XXXXX-X"!=l._getAccount()?l._trackSocial("Google",g,h):window._gaq&&window._gaq.push(["_trackSocial","Google",g,h])}catch(b){}if(window.ga&&window.ga.getAll)try{for(var q=window.ga.getAll(),l=0;l<q.length;l++)q[l].send("social","Google",g,h)}catch(t){}}if(cB&&window.dataLayer)try{window.dataLayer.push({event:"social",socialNetwork:"Google",socialAction:g,
socialTarget:h})}catch(v){}}a.call(this,f)}};var mx=function(a){return _.$&&a instanceof _.$};var Tt=function(a,c){if(c.onready){var f=!1,g=function(){f||(f=!0,c.onready.call(null))};a.Q(mx(a)?"_ready":"ready",g,_.V.Fa);a.Q(mx(a)?"_renderstart":"renderstart",g,_.V.Fa)}(0,_.tB)(a)};
var sw=function(a,c,f){function g(){t||(t=!0,h(),f&&Sd("wrrt",l,b),Sd("wrri",l,b))}function h(){q||(q=!0,f&&Sd("wrdt",l,b),Sd("wrdi",l,b))}var l=a.Fb,b=String(a.Kj),q=!1;c.Q(mx(c)?"_renderstart":"renderstart",h,_.V.Fa);var t=!1;c.Q(mx(c)?"_ready":"ready",g,_.V.Fa);_.$&&c instanceof _.$?c.Q("widget-interactive-"+c.id,g,_.V.Fa):_.T.Q("widget-interactive-"+c.id,g);_.T.Q("widget-csi-tick-"+c.id,function(a,c,f){"wdc"===a||"wci"===a?Sd("wdc",l,b,f):"wje0"===a||"wji_"===a?Sd("wje0",l,b,f):"wje1"===a||"wji"===
a?Sd("wje1",l,b,f):"wh0"==a?nf("wh0",l,b,f):"wh1"==a&&nf("wh1",l,b,f)})};var nx=function(a){return"number"==typeof a?a+"px":"100%"==a?a:null};var Ut=function(a,c){function f(f){f=f||a;var h=nx(f.width);h&&c.style.width!=h&&(c.style.width=h);(f=nx(f.height))&&c.style.height!=f&&(c.style.height=f)}mx(a)?a.Vm("onRestyle",f):(a.Q("ready",f,_.V.Fa),a.Q("renderstart",f,_.V.Fa),a.Q("resize",f,_.V.Fa))};
var eC=function(a,c){for(var f in Mt)if(Mt.hasOwnProperty(f)){var g=Mt[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};var fC=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||gg)(c[g.toLowerCase()],c,gC));return f};var hC=function(a){if(a=a.Or)for(var c=0;c<a.length;c++)(new window.Image).src=a[c]};
var ox=function(a,c){var f=c.userParams,g=c.siteElement;g||(g=(g=c.iframeNode)&&g.parentNode);if(g&&1===g.nodeType){var h=fC(a.Ca,f);a.Dm.push({element:g,Ca:h,pe:eC(h,fC(a.Jr,f)),Sg:3,xp:!!f["data-onload"],Xr:c})}f=a.Dm;for(g=a.bj;0<f.length;)g(f.shift())};
_.iC=function(a){function c(){"onload"===jC&&g.go()}var f=Jt(a);hC(f);(0,_.ql)(f.Fb,function(a){ox(f,a)});Bd[f.Fb]=!0;var g={ca:function(a,c){var g=c||{};g.type=f.Fb;var q=g.type;delete g.type;var t=("string"===typeof a?window.document.getElementById(a):a)||void 0;if(t){var v={},w;for(w in g)(0,_.Qa)(g,w)&&(v[w.toLowerCase()]=g[w]);v.rd=1;(g=!!v.ri)&&delete v.ri;Hd(q,t,v,[],0,g)}else(0,_.kd)("string"==="gapi."+q+".render: missing element "+typeof a?a:"")},go:function(a){xd(a,f.Fb)},B:function(){var a=
(0,_.N)(_.Hb,"WI",(0,_.O)()),c;for(c in a)delete a[c]}};$w(f.Fb)||(0,_.vd)(c,c);(0,_.d)("gapi."+f.Fb+".go",g.go);(0,_.d)("gapi."+f.Fb+".render",g.ca);return g};_.tB=function(){};
var px=function(a,c){a.Kj++;Sd("wrs",a.Fb,String(a.Kj));var f=c.userParams,g=fC(a.Ca,f),h=[],l=c.iframeNode,b=c.siteElement,q=St(a,g),t=eC(g,fC(a.Jr,f)),f=!!f["data-onload"],v=_.Sm,w=(0,_.O)();w.renderData=c;w.height=g.height;w.width=g.width;w.id=c.id;w.url=c.url;w.iframeEl=l;w.where=w.container=b;w.apis=["_open"];w.messageHandlers=q;w.messageHandlersFilter=_.Vz;(0,_.Ww)(w);a.qe&&(h[2]=w,h[3]=t,h[4]=q,a.qe("i",h));l=v.Pe(w);l.id=c.id;l.eC(l,w);Tt(l,g);Ut(l,b);sw(a,l,f);h[5]=l;a.qe&&a.qe("e",h)}; var Nd={button:!0,div:!0,span:!0};
var cx={callback:-1,clientid:1,cookiepolicy:1,requestvisibleactions:1,scope:1},bx=!1,dx=(0,_.O)();var jx={post:!0},ix={post:!0},Md={style:"position:absolute;top:-10000px;width:450px;margin:0px;border-style:none"},Ld="onPlusOne _ready _close _open _resizeMe _renderstart oncircled drefresh erefresh".split(" "),id=(0,_.N)(_.Hb,"WI",(0,_.O)()),Gd=["style","data-gapiscan"];
var Bd,Cd,Dd,Fd,gx=/(?:^|\s)g-((\S)*)(?:$|\s)/,hx={plusone:!0,autocomplete:!0,profile:!0};Bd=(0,_.N)(_.Hb,"SW",(0,_.O)());Cd=(0,_.N)(_.Hb,"SA",(0,_.O)());Dd=(0,_.N)(_.Hb,"SM",(0,_.O)());Fd=(0,_.N)(_.Hb,"FW",[]);(0,_.N)(_.Yi,"platform",{}).go=xd;var Rd=(0,_.N)(_.Hb,"perf",(0,_.O)()),yd=(0,_.N)(Rd,"g",(0,_.O)()),Ud=(0,_.N)(Rd,"i",(0,_.O)());(0,_.N)(Rd,"r",[]);var Pd=(0,_.O)(),Qd=(0,_.O)();(function(){function a(a){this.t={};this.tick=function(a,c,f){this.t[a]=[void 0!=f?f:(new Date).getTime(),c]};this.tick("start",null,a)}var c=new a;window.__gapi_jstiming__={Timer:a,load:c};if(window.performance&&window.performance.timing){var c=window.performance.timing,f=window.__gapi_jstiming__.load,g=c.navigationStart,c=c.responseStart;0<g&&c>=g&&(f.tick("_wtsrt",void 0,g),f.tick("wtsrt_","_wtsrt",c),f.tick("tbsd_","wtsrt_"))}try{c=null,window.chrome&&window.chrome.csi&&(c=Math.floor(window.chrome.csi().pageT),
f&&0<g&&(f.tick("_tbnd",void 0,window.chrome.csi().startE),f.tick("tbnd_","_tbnd",g))),null==c&&window.gtbExternal&&(c=window.gtbExternal.pageT()),null==c&&window.external&&(c=window.external.pageT,f&&0<g&&(f.tick("_tbnd",void 0,window.external.startE),f.tick("tbnd_","_tbnd",g))),c&&(window.__gapi_jstiming__.pt=c)}catch(h){}})();
if(window.__gapi_jstiming__){window.__gapi_jstiming__.Pz={};window.__gapi_jstiming__.Yr=1;var he=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],void 0!=f?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=he;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};var ie=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var l=window.chrome;if(l&&(l=l.loadTimes)){l().wasFetchedViaSpdy&&(g+="&p=s");if(l().wasNpnNegotiated){var g=g+"&npn=1",b=l().npnNegotiatedProtocol;b&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(b))}l().wasAlternateProtocolAvailable&&(g+="&apa=1")}var q=a.t,t=q.start,l=[],b=[],v;for(v in q)if("start"!=v&&0!=v.indexOf("_")){var w=q[v][1];w?q[w]&&
b.push(v+"."+he(a,v,q[w][0])):t&&l.push(v+"."+he(a,v))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");return[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,b.length?"&it="+b.join(","):"",g,"&rt=",l.join(",")].join("")},je=function(a,c,f){a=ie(a,c,f);if(!a)return"";c=new window.Image;var g=window.__gapi_jstiming__.Yr++;window.__gapi_jstiming__.Pz[g]=c;c.onload=c.onerror=
function(){window.__gapi_jstiming__&&delete window.__gapi_jstiming__.Pz[g]};c.src=a;c=null;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=!1,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var l;"prerender"==window.document.webkitVisibilityState?l=!1:(je(a,c,f),l=!0);l&&(g=!0,window.document.removeEventListener("webkitvisibilitychange",h,!1))}};window.document.addEventListener("webkitvisibilitychange",h,!1);return""}return je(a, c,f)}};
var fe=[73,74,77,78],ee={g:"gapi_global",m:"gapi_module",w:"gwidget"};Wd.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.B;case "w":return this.type+"."+this.name+this.B}};var ce=new Wd,Yd=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/),$d=(0,_.N)(Rd,"_c",(0,_.O)()),ae=Math.random()<((0,_.P)("csi/rate")||0);Od("blt","bs0","bs1");Od("psi","ps0","ps1");Od("rpcqi","rqe","rqd");Od("mli","ml0","ml1");
Od("mei","me0","me1",!0);Od("wci","wrs","wdc");Od("wdi","wrs","wrdi");Od("wdt","bs0","wrdt");Od("wri","wrs","wrri",!0);Od("wrt","bs0","wrrt");Od("wji","wje0","wje1",!0);Od("wjli","wjl0","wjl1");Od("whi","wh0","wh1",!0);Od("wai","waaf0","waaf1",!0);Od("wadi","wrs","waaf1",!0);Od("wadt","bs0","waaf1",!0);var qx=Rd.r;if("function"!==typeof qx){for(var rx;rx=qx.shift();)Zd.apply(null,rx);Rd.r=Zd};
var Rt=["div"],jC="onload",zx=!0,cB=!0,gC=null,gC=(0,_.P)();(0,_.P)("gwidget");var sx=Kg("parsetags"),jC="explicit"===sx||"onload"===sx?sx:jC,tx=Kg("google_analytics");"undefined"!==typeof tx&&(zx=!!tx);var ux=Kg("data_layer");"undefined"!==typeof ux&&(cB=!!ux);var Mt=function(){var a={};a.width=[Uj(450)];a.height=[Uj(24)];a.onready=[En];a.lang=[Ft,"hl"];a.iloader=[function(){return _.Hb.ILI},"iloader"];return a}();
var wx=ox,ox=function(a,c){var f=c.url;a.bL||(0,_.Zw)(f)?_.Cl?px(a,c):(0,_.At)("gapi.iframes.impl",function(){px(a,c)}):_.V.open?wx(a,c):(0,_.At)("iframes",function(){wx(a,c)})};
var od=function(a,c){if("string"==typeof a){a=a.toLowerCase();var f;for(f=0;f<c.length;f++)if(c[f]==a)return a}};_.pd=function(a){return od(a,qd)};var rd=function(a){return od(a,sd)};_.td=function(a){a.source=[null,"source"];a.expandTo=[null,"expandTo"];a.align=[rd];a.annotation=[_.pd];a.origin=[_.md]};var qd="inline bubble none only pp vertical-bubble".split(" "),sd=["left","right"];

_.Tz=function(){this.Rd=this.Kf=null;this.Gh=!1};_.Tz.prototype.lc=function(a){if(this.Kf){var c=this.Kf;a instanceof _.Tz?a.Ed(c):c(a);this.Kf=null}else this.Rd=a,this.Gh=!0};_.Tz.prototype.Ed=function(a){this.Kf=a;if(this.Gh){var c=this.Rd;c instanceof _.Tz?c.Ed(a):a(c);this.Gh=!1;this.Rd=null}};

var Xz;var Zz;_.Uz=function(a){return a.Db===a.getContext().Db};_.Vz=function(){return!0};_.AD=function(a){for(var c=(0,_.O)(),f=0;f<a.length;f++)c[a[f]]=!0;return function(a){return!!c[a.Db]}};
var Wz=function(a,c){var f=Xz[a];return function(a){if(!c.Ma()&&((0,_.fb)(this.origin===c.Db,"Wrong origin "+this.origin+" != "+c.Db),f&&0<f.length))for(var h=[],l=this.callback,b=f.length,q=0;q<f.length;q++){var t=f[q].call(c,a,c),v=(0,_.ma)(function(a,f){h[a]=f;0===--b&&(c.Ma()||l(h))},q);if(t&&!(t instanceof _.Tz||"object"!==typeof t&&"function"!==typeof t||"function"!==typeof t.then)){var w=new _.Tz;t.then(function(a){w.lc(a)});t=w}t&&t instanceof _.Tz?t.Ed(v):v(t)}}};
_.Yz=function(a,c,f){(0,_.fb)("_default"!=a,"Cannot update default api");Zz[a]={map:c,filter:f}};_.$z=function(a,c,f){(0,_.fb)("_default"!=a,"Cannot update default api");(0,_.N)(Zz,a,{map:{},filter:_.Uz}).map[c]=f};_.aA=function(a,c){(0,_.N)(Zz,"_default",{map:{},filter:_.Vz}).map[a]=c;(0,_.DC)(_.Sm.B,function(f){f.Q(a,c,_.Vz)})};_.Cl=function(){return _.Sm};
_.bA=function(a){a=a||{};this.cm=!1;this.yd=(0,_.O)();this.B=(0,_.O)();this.Ka=a._window||_.Ia;this.ha=this.Ka.location.href;this.dc=(this.df=this.Ka.document.referrer||(0,_.Ua)(this.ha,"parent",""))?(0,_.Ua)(this.ha,"pfname",""):"";this.Rj=(this.qa=this.df?(0,_.Ua)(this.ha,"id",""):"")?this.dc+"/"+this.qa:"";this.Db=_.Rb.Pq(this.ha);if(this.qa){var c={};c.rpcAddr=a._parentRpcAddr||"..";c.retAddr=a._parentRetAddr||this.qa;c.origin=_.Rb.Pq((0,_.Ua)(this.ha,"parent",this.ha));c.frameName=this.dc;this.G=
this.Pe(c)}else this.G=null};var cA=function(a,c,f){var g=c.canvasUrl;if(!g)return f;(0,_.fb)(!c.allowPost,"Post is not supported when using canvas url");var h=c.url;(0,_.fb)(h&&_.Rb.Pq(h)===a.Db&&_.Rb.Pq(g)===a.Db,"Wrong origin for canvas or hidden url "+g);c.url=g;c.waitForOnload=!0;delete c.canvasUrl;return function(a){var c=a.Aa(),g=c.location.hash,g=(0,_.Bl)(h)+(/#/.test(h)?g.replace(/^#/,"&"):g);c.location.replace(g);f&&f(a)}};
var dA=function(a,c,f){var g=c.relayOpen;if(g){var h=a.G;g instanceof _.$?(h=g,c.relayOpen=0):0<g&&(c.relayOpen=g-1);if(h){delete c.openerIframe;(0,_.fb)(!!h.SE,"Relaying iframe open is disabled");if(g=c.style)if(g=_.eA[g])c.context=a,g(c),c.context=void 0;h.SE(c,f);return!0}}return!1};
var fA=function(a,c,f){var g=c.style;if(g)if((0,_.fb)(!!_.gA,"Defer style is disabled, when requesting style "+g),_.hA[g])a.zt(c);else return iA(g,function(){(0,_.fb)(!!_.hA[g],"Fail to load style - "+g);a.open(c,f)}),!0;return!1};_.$=function(a,c,f,g){this.cm=!1;this.Xh=a;this.Nc=c;this.Rj=f;this.zd=g;this.re=g.retAddr;this.Db=g.origin;this.dJ=g.iframeEl;this.CF=g.where;this.Tx=[];this.Ce("_default");if((0,_.Qa)(g,"apis"))for(a=g.apis||[],c=0;c<a.length;c++)this.Ce(a[c]);this.Xh.B[f]=this};
_.jA=function(a,c,f,g){a.send(c,f,g,_.Vz)};_.gA=function(a){return _.hA[a]};var iA=function(a,c){_.Yi.load("gapi.iframes.style."+a,c)};_.Dl=function(a){"number"===typeof a&&(a=String(a)+"px");return a};var lA=function(a,c){function f(a){if(a&&h){var f;c.Ga&&c.pn&&(f=function(){c.Ga(!0)});c.um&&c.um.call(g,c.Ya);c.sender?c.sender(c.Ya,f):(0,_.jA)(h,c.message,c.Ya,f);c.Ga&&!c.pn&&c.Ga(!0)}else c.Ga&&c.Ga(!1)}var g=a,h=g.G,l=!0;c.filter&&(l=c.filter.call(c.qg,c.Ya));l instanceof _.Tz?l.Ed(f):f(l)}; _.mA=function(a,c){var f={};if(c)for(var g in c)(0,_.Qa)(c,g)&&(0,_.Qa)(nA,g)&&oA.test(c[g])&&(f[g]=c[g]);return f};
var Rl=/^[\w\.\-]*$/;_.k=_.bA.prototype;_.k.Ma=function(){return this.cm};_.k.ta=function(){if(!this.Ma()){for(var a=0;a<this.B.length;a++)this.B[a].ta();this.cm=!0}};_.k.Tp=function(){return this.Rj};_.k.Aa=function(){return this.Ka};_.k.sj=function(a,c){this.yd[a]=c};_.k.$h=function(a){return this.yd[a]};
_.k.Pe=function(a){(0,_.fb)(!this.Ma(),"Cannot attach iframe in disposed context");a.rpcAddr||(a.rpcAddr=a.id);a.retAddr||(a.retAddr="..");a.origin||(a.origin=_.Rb.Pq(a.url));a.frameName||(a.frameName=a.id?this.Rj+"/"+a.id:"");var c=a.frameName;if(this.B[c])return this.B[c];var f=a.rpcAddr,g=f;(0,_.Qa)(a,"origin")&&(g=f+"|"+a.origin);var h=a.retAddr,l=a.rpctoken;l||(l=(l=a.iframeEl)&&(l.getAttribute("data-postorigin")||l.src)||a.url,l=(0,_.Ua)(l,"rpctoken"));a._rpcReadyFn=(0,_.Mz)(g,h,l,a._popupWindow);
g=((window.gadgets||{}).rpc||{}).setAuthToken;l&&g&&g(f,l);var b=new _.$(this,f,c,a),q=a.messageHandlersFilter;(0,_.DC)(a.messageHandlers,function(a,c){b.Q(c,a,q)});a.setRpcReady&&b.vj();(0,_.jA)(b,"_g_rpcReady");return b};_.k.ZB=function(a){delete a.frameName;var c=a.id;!c||Rl.test(c)&&!this.Aa().document.getElementById(c)||((0,_.kd)("Ignoring requested iframe ID - "+c),delete a.id)};
_.k.cj=function(a){(0,_.fb)(!this.Ma(),"Cannot open iframe in disposed context");this.zt&&this.zt(a);var c=a.frameName;if(c&&this.B[c])return this.B[c];this.ZB(a);c=a.url;(0,_.fb)(c,"No url for new iframe");(a.queryParams=a.queryParams||{}).usegapi="1";a.pfname=this.Rj;var f=this.xu&&this.xu(c,a);if(!f){var g=a.where;(0,_.fb)(!!g,"No location for new iframe");g=(0,_.tb)(c,g,a);a.iframeEl=g;f=g.getAttribute("id")}a.rpcAddr=a.id=f;a.origin=_.Rb.Pq(a.eurl);this.te&&this.te(a,g);c=this.Pe(a);c.eC&&c.eC(c,
a);if("function"===typeof a.onCreate)a.onCreate(c);a.disableRelayOpen||c.Ce("_open");return c};_.k.open=function(a,c){(0,_.fb)(!this.Ma(),"Cannot open iframe in disposed context");var f=cA(this,a,c),g=a.url;g&&(a.url=(0,_.Bl)(g));if(!(dA(this,a,f)||fA(this,a,f)||dA(this,a,f))){var h,g=function(){f&&f(h)};a.waitForOnload&&((0,_.N)(a,"attributes",{}).onload=g);h=this.cj(a);a.waitForOnload||g()}};_.k.cq=function(){return this.G};_.k=_.$.prototype;_.k.Ma=function(){return this.cm};
_.k.ta=function(){if(!this.Ma()){for(var a=0;a<this.Tx.length;a++)this.Jd(this.Tx[a]);delete _.Sm.B[this.Tp()];this.cm=!0}};_.k.getContext=function(){return this.Xh};_.k.Tp=function(){return this.Rj};_.k.Mc=function(){return this.dJ};_.k.V=function(){return this.CF};_.k.qc=function(a){this.CF=a};_.k.vj=function(){this.zd._rpcReadyFn()};_.k.Vm=function(a,c){this.zd[a]=c};_.k.Zf=function(a){return this.zd[a]};_.k.va=function(){return this.zd};_.k.Hh=function(){return this.zd.id};_.k.Pq=function(){return this.Db};
_.k.Q=function(a,c,f){(0,_.fb)(!this.Ma(),"Cannot register handler on disposed iframe "+a);(0,_.fb)((f||_.Uz)(this),"Rejecting untrusted message "+a);f=this.Rj+":"+this.Xh.Rj+":"+a;1==(0,_.N)(Xz,f,[]).push(c)&&(this.Tx.push(a),(0,_.sz)(f,Wz(f,this)))};_.k.Jd=function(a,c){var f=this.Rj+":"+this.Xh.Rj+":"+a,g=Xz[f];if(g){if(c){var h=_.Nb.call(g,c);0<=h&&g.splice(h,1)}else g.splice(0,g.length);0==g.length&&(h=_.Nb.call(this.Tx,a),0<=h&&this.Tx.splice(h,1),(0,_.wz)(f))}};_.k.fq=function(){return this.Tx};
_.k.Ce=function(a){this.mA=this.mA||[];if(!(0<=_.Nb.call(this.mA,a))){this.mA.push(a);a=Zz[a]||{map:{}};for(var c in a.map)(0,_.Qa)(a.map,c)&&this.Q(c,a.map[c],a.filter)}};_.k.send=function(a,c,f,g){(0,_.fb)(!this.Ma(),"Cannot send message to disposed iframe - "+a);(0,_.fb)((g||_.Uz)(this),"Wrong target for message "+a);(0,_.Az)(this.Nc,this.Xh.Rj+":"+this.Rj+":"+a,f,c)};_.k.WJ=function(a){return a};_.k.VJ=function(a,c){(0,_.jA)(this,"_g_ping",c,a)};Xz=(0,_.O)();Zz=(0,_.O)();_.Sm=new _.bA; (0,_.aA)("_g_rpcReady",_.$.prototype.vj);(0,_.aA)("_g_discover",_.$.prototype.fq);(0,_.aA)("_g_ping",_.$.prototype.WJ);
_.hA=(0,_.O)();_.eA=(0,_.O)();_.bA.prototype.zt=function(a){var c=a.style;if(c){delete a.style;var f=_.hA[c];(0,_.fb)(f,"No such style: "+c);a.context=this;f(a);a.context=void 0}};var nA={height:!0,width:!0},oA=/^(?!-*(?:expression|(?:moz-)?binding))(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,2}|%)?|!important|)$/i;_.$.prototype.Aa=function(){if(!(0,_.Uz)(this))return null;var a=this.zd._popupWindow;if(a)return a;for(var c=this.Nc.split("/"),a=this.getContext().Aa(),f=0;f<c.length&&a;f++)var g=c[f],a=".."===g?a==a.parent?a.opener:a.parent:a.frames[g];return a};
_.bA.prototype.Ld=function(a,c,f){lA(this,{sender:function(a,c){var f=_.Sm.G;(0,_.DC)(_.Sm.B,function(a){a!==f&&(0,_.jA)(a,"_g_wasClosed")});(0,_.jA)(f,"_g_closeMe",a,c);(0,_.jA)(f,"_g_wasClosed")},message:"_g_closeMe",Ya:a,Ga:c,qg:f,filter:this.$h("onCloseSelfFilter")})};_.bA.prototype.po=function(a,c,f){a=a||{};lA(this,{message:"_g_restyleMe",Ya:a,Ga:c,qg:f,filter:this.$h("onRestyleSelfFilter"),pn:!0,um:this.Ph})};_.bA.prototype.Ph=function(a){"auto"===a.height&&(a.height=_.Ob.ih())};_.k=_.$.prototype;
_.k.close=function(a,c){(0,_.jA)(this,"_g_close",a,c)};_.k.sD=function(a,c){(0,_.jA)(this,"_g_restyle",a,c)};_.k.ds=function(a,c){(0,_.jA)(this,"_g_restyleDone",a,c)};_.k.qp=function(a){var c=new _.Tz;this.getContext().Ld(a,function(a){c.lc(a)},this);return c};_.k.tD=function(a){var c=new _.Tz;this.getContext().po(a,function(a){c.lc(a)},this);return c};
_.k.fs=function(a){var c=this.Zf("onRestyle");c&&c.call(this,a);a=(0,_.mA)(this,a);(c=this.Mc())&&a&&"object"===typeof a&&((0,_.Qa)(a,"height")&&(a.height=(0,_.Dl)(a.height)),(0,_.Qa)(a,"width")&&(a.width=(0,_.Dl)(a.width)),(0,_.Ra)(a,c.style))};_.k.rp=function(a){var c=this.Zf("onClose");c&&c.call(this,a);this.lD&&this.lD()||(a=this.Mc())&&a.parentNode&&a.parentNode.removeChild(a);if(a=this.zd.controller)c={},c.frameName=this.Tp(),(0,_.jA)(a,"_g_disposeControl",c)};
_.bA.prototype.Th=function(a){this.sj("onCloseSelfFilter",a)};_.bA.prototype.Ej=function(a){this.sj("onRestyleSelfFilter",a)};_.$.prototype.aK=function(a,c){this.Q("_g_wasRestyled",a,c)};_.$.prototype.WB=function(a,c){this.Q("_g_wasClosed",a,c)};_.$.prototype.eL=function(){this.getContext().Aa().setTimeout((0,_.H)(function(){this.ta()},this),0)};(0,_.aA)("_g_close",_.$.prototype.qp);(0,_.aA)("_g_closeMe",_.$.prototype.rp);(0,_.aA)("_g_restyle",_.$.prototype.tD);(0,_.aA)("_g_restyleMe",_.$.prototype.fs); (0,_.aA)("_g_wasClosed",_.$.prototype.eL);

var ZA=function(a,c,f){var g=a.Nc,h=c.re;f.rpcAddr=a.re+"/"+c.Nc;f.retAddr=h+"/"+g;f.frameName=c.Tp();f.origin=c.Db};var dB=function(a){a.ye||(a.ye=(0,_.O)(),a.Kh=(0,_.O)())};var eB=function(a,c,f,g){g=g||[];for(var h=0;h<g.length;h++){var l=g[h];if(l&&c&&c&&l.filter.call(a,c)){for(var b=0;b<l.hk.length;b++)c.Ce(l.hk[b]);l.Tc&&l.Tc(c,f);g[h]!==l&&h--}}};
var fB=/^https?:\/\/[^\/%\\?#\s]+$/i,bB={longdesc:!0,name:!0,src:!0,frameborder:!0,marginwidth:!0,marginheight:!0,scrolling:!0,align:!0,height:!0,width:!0,id:!0,"class":!0,title:!0,tabindex:!0,hspace:!0,vspace:!0,allowtransparency:!0};
_.bA.prototype.Ei=function(a,c){var f=c||{},g=a.setRpcReady,h=a.iframe,l=f.iframe,b=a.rpctoken;if(l){var q={};ZA(h,l,q);q.rpctoken=b;q.role=a.role;q.data=a.data;q.setRpcReady=g;var t={};ZA(l,h,t);t.rpctoken=b;t.role=f.role;t.data=f.data;t.setRpcReady=1;(0,_.jA)(h,"_g_connect",q,function(){g||(0,_.jA)(l,"_g_connect",t)});g&&(0,_.jA)(l,"_g_connect",t)}else f={selfConnect:1},f.role=a.role,f.data=a.data,(0,_.jA)(h,"_g_connect",f)};_.k=_.$.prototype;
_.k.wH=function(a){var c;a=a||{};a.selfConnect||(0,_.fb)(fB.test(a.origin),"Illegal origin for connected iframe - "+a.origin);if(a.selfConnect)c=this;else{var f={};f.rpctoken=a.rpctoken;f.rpcAddr=a.rpcAddr;f.retAddr=a.retAddr;f.origin=a.origin;c=f.frameName=a.frameName;var g=f.setRpcReady=a.setRpcReady;c=this.Xh.B[c];c?g&&(c.vj(),(0,_.jA)(c,"_g_rpcReady")):c=this.Xh.Pe(f)}f=this.Xh;g=a.role||"";a=a.data;dB(f);g=g||"";(0,_.N)(f.ye,g,[]).push({qg:c.Tp(),data:a});eB(f,c,a,f.Kh[g])};
_.k.eC=function(a,c){c._relayedDepth||(0,_.jA)(a,"_g_connect",{role:"_opener",selfConnect:1})};
_.k.SE=function(a,c){var f=this,g=a.messageHandlers,h=a.messageHandlersFilter,l=a.onClose;a.messageHandlers=null;a.messageHandlersFilter=null;a.onClose=null;(0,_.jA)(this,"_g_open",a,function(b){var q=b[0],t=q.frameName;b={};var v=f.re,w=q.retAddr;b.rpcAddr=f.Nc+"/"+q.rpcAddr;b.retAddr=w+"/"+v;b.frameName=t;b.origin=q.origin;b.apis=q.apis;b.rpctoken=a.rpctoken;b.messageHandlers=g;b.messageHandlersFilter=h;b.onClose=l;(q=f.Xh.B[t])||(q=f.Xh.Pe(b));c&&c(q)})};
_.k.ZB=function(a){(0,_.fb)(!a.url||(0,_.xa)(a.url),"Illegal url for new iframe - "+a.url);var c=a.attributes||{},f={},g;for(g in c)(0,_.Qa)(c,g)&&(0,_.Qa)(bB,g)&&(f[g]=c[g]);(0,_.Qa)(c,"style")&&(c=c.style,"object"===typeof c&&(f.style=(0,_.mA)(this,c)));a.attributes=f};
_.k.OJ=function(a){a=a||{};this.ZB(a);var c=a._relayedDepth||0;a._relayedDepth=c+1;a.openerIframe=this;var f=new _.Tz,g=a.rpctoken;delete a.rpctoken;this.Xh.open(a,(0,_.H)(function(a){var l=a.zd.apis,b={};ZA(a,this,b);0==c&&(b.role="_opener");b.setRpcReady=1;b.rpctoken=g;(0,_.jA)(a,"_g_connect",b);b={};b.apis=l;b.rpcAddr=a.Nc;b.retAddr=a.re;b.frameName=a.Tp();b.origin=a.Db;f.lc(b)},this));return f};
_.bA.prototype.wc=function(a,c,f,g){dB(this);f=f||[];a=a||"";c={filter:g||_.Uz,Tc:c,hk:f};(0,_.N)(this.Kh,a,[]).push(c);a=this.ye[a]||[];for(g=0;g<a.length;g++)eB(this,this.B[a[g].qg],a[g].data,[c])};_.bA.prototype.Bg=function(a,c){var f=(0,_.N)(this.Kh,a,[]);if(c)for(var g=0,h=!1;!h&&g<f.length;g++)f[g].Tc===c&&(h=!0,f.splice(g,1));else f.splice(0,f.length)};_.bA.prototype.M=function(a,c,f){function g(c){h.Bg("_opener",g);a&&a.call(this,c)}var h=this;this.wc("_opener",g,c,f)};
_.$.prototype.jK=function(a){this.getContext().M(function(c){c.send("_g_wasRestyled",a,void 0,_.Vz)},null,_.Vz)};var gB=_.Sm.G;gB&&gB.Q("_g_restyleDone",_.$.prototype.jK,_.Vz);(0,_.aA)("_g_connect",_.$.prototype.wH);var hB={};hB._g_open=_.$.prototype.OJ;(0,_.Yz)("_open",hB,_.Vz);


_.At=(window.gapi||{}).load;
_.V.qj("bubble",function(a){(0,_.At)("iframes-styles-bubble",a)});
_.V.qj("slide-menu",function(a){(0,_.At)("iframes-styles-slide-menu",a)});
var xv;var wv=function(a,c,f){a=(0,_.pd)(a);c=(0,_.cd)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.dd[c]["false"].height};if("bubble"!=a){if("none"==a)return _.dd[c]["false"];if("pp"==a)return xv}}return _.dd[c]["true"]};xv={width:180,height:35};
_.Wa=_.Xa=function(){var a={0:"plusone"},c=(0,_.P)("iframes/plusone/preloadUrl");c&&(a[7]=c);(0,_.td)(_.hd);a[1]=_.hd;a[2]={width:[function(a,c){return c.annotation?wv(c.annotation,c.size,c).width:_.dd[(0,_.cd)(c.size)][(0,_.ed)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?wv(c.annotation,c.size,c).height:_.dd[(0,_.cd)(c.size)][(0,_.ed)(c.count,c.size)].height}]};a[3]={onPlusOne:{Kg:function(a){return"on"==a.state?"+1":null},Qh:"callback"},onstartinteraction:!0,onendinteraction:!0, onpopup:!0};a[4]=["div","button"];return(0,_.iC)(a)}();

});

// Copyright 2002-2013 Google Inc.
