.PHONY: all

all: compile

compile:
	$(JAVAC) *.java
	$(JAVAC) units-extension/*.java

# TODO: type check the different files with the right checker;
#   some tests expect errors, compare against expected errors.
